(print "if-dyn-3" ((jit (lambda (x) (if (< x 5) 1 0))) 3))
(print "if-dyn-7" ((jit (lambda (x) (if (< x 5) 1 0))) 7))
(print "and-tt" ((jit (lambda () (and true true)))))
(print "and-tf" ((jit (lambda () (and true false)))))
(print "or-ft" ((jit (lambda () (or false true)))))
(print "or-ff" ((jit (lambda () (or false false)))))
(print "coalesce" ((jit (lambda (a b c) (coalesce a b c))) nil false 42))
(print "coalesceNil" ((jit (lambda (a b c) (coalesceNil a b c))) nil nil 42))
(exit)
