(print "S1")
(define jit_substr2 (jit (lambda (s i) (substr s i))))
(print "S2")
(define jit_substr3 (jit (lambda (s i n) (substr s i n))))
(print "S3")
(define _jit_id (lambda (x) x))
(print "S4")
(equal? (jit_substr2 "abcdef" 0) (substr "abcdef" 0))
(print "S5")
(equal? (jit_substr2 "abcdef" 1) (substr "abcdef" 1))
(print "S6")
(equal? (jit_substr2 "abcdef" 5) (substr "abcdef" 5))
(print "S7")
(equal? (jit_substr3 "abcdef" 0 3) (substr "abcdef" 0 3))
(print "S8")
(equal? (jit_substr3 "abcdef" 1 3) (substr "abcdef" 1 3))
(print "S9")
(equal? (jit_substr3 "abcdef" 3 0) (substr "abcdef" 3 0))
(print "S10")
(equal? (jit_substr3 "abcdef" 3 3) (substr "abcdef" 3 3))
(print "S11")
(equal? (jit_substr3 "abcdef" (+ 1 1) (+ 1 2)) (substr "abcdef" (+ 1 1) (+ 1 2)))
(print "S12")
(equal? (jit_substr2 (_jit_id 123456) 2) (substr (_jit_id 123456) 2))
(print "S13")
(equal? (jit_substr3 (_jit_id 123456) 2 3) (substr (_jit_id 123456) 2 3))
(print "S14")
(equal? (jit_substr2 "abcdef" 2.0) (substr "abcdef" 2.0))
(print "S15")
(equal? (jit_substr3 "abcdef" 1.0 3.0) (substr "abcdef" 1.0 3.0))
(print "S16")
(equal? (jit_substr3 "äöüxyz" 0 6) (substr "äöüxyz" 0 6))
(print "S17")
((jit (lambda (s) (toUpper s))) "hello")
(print "S18")
((jit (lambda (s) (toLower s))) "HELLO")
(print "S19")
((jit (lambda (s) (strlike s "hello"))) "hello")
(print "S20")
((jit (lambda (s) (strlike s "h%"))) "hello")
(print "S21")
((jit (lambda (s p) (strlike s p))) "hello" "h%")
(print "S22")
((jit (lambda (x) (+ (* x x) (* 2 x) 1))) 3)
(print "S23")
((jit (lambda (x) (+ (* x x) (* 2 x) 1))) 5)
(print "S24")
((jit (lambda (a b) (* (+ a b) (- a b)))) 7 3)
(print "S25")
((jit (lambda (x) (* (+ x 1) (+ x 2)))) 3)
(print "S26")
((jit (lambda (x) (- (* 3 (* x x)) (* 2 x)))) 4)
(print "S27")
((jit (lambda (a b c) (+ (* a a) (* b b) (* c c)))) 3 4 5)
(print "S28")
((jit (lambda (a b c) (* (+ a b) (+ b c) (+ a c)))) 1 2 3)
(print "S29")
((jit (lambda (x) (+ (* (* x x) x) (* x x) x 1))) 2)
(print "S30")
((jit (lambda (x) (+ (* x 10) (* x 5) (* x 1)))) 3)
(print "S31")
((jit (lambda (x) (* (+ x 1) (- x 1)))) 5)
(print "S32")
((jit (lambda (a b) (+ (* 3 a) (* 4 b)))) 2 5)
(print "S33")
((jit (lambda (a b) (- (* a b) (+ a b)))) 6 4)
(print "DONE")
