(define run (lambda (name expr)
  (print "RUN " name)
  (print "RES " expr)
))
(run "x+1" ((jit (lambda (x) (+ x 1))) 4))
(run "x-3" ((jit (lambda (x) (- x 3))) 10))
(run "x*2" ((jit (lambda (x) (* x 2))) 5))
(run "a+b" ((jit (lambda (a b) (+ a b))) 3 4))
(run "a*b" ((jit (lambda (a b) (* a b))) 3 4))
(run "a-b" ((jit (lambda (a b) (- a b))) 10 3))
(run "(x+1)*2" ((jit (lambda (x) (* (+ x 1) 2))) 4))
(run "x*2+1" ((jit (lambda (x) (+ (* x 2) 1))) 4))
(run "a*b+c" ((jit (lambda (a b c) (+ (* a b) c))) 3 4 5))
(run "a*b+c*d" ((jit (lambda (a b c d) (+ (* a b) (* c d)))) 2 3 4 5))
(run "nested+" ((jit (lambda (x) (+ (+ (+ x 1) 2) 3))) 10))
(run "nested*" ((jit (lambda (x) (* (* (* x 2) 2) 2))) 3))
(run "a2-b2" ((jit (lambda (a b) (- (* a a) (* b b)))) 5 3))
(run "a+(b-c)" ((jit (lambda (a b c) (+ a (- b c)))) 10 7 3))
(run "if<" ((jit (lambda (x) (if (< x 5) 1 0))) 3))
(run "if<2" ((jit (lambda (x) (if (< x 5) 1 0))) 7))
(run "and" ((jit (lambda () (and true true)))))
(run "or" ((jit (lambda () (or false true)))))
(run "bool+" ((jit (lambda (x) (and (> x 0) (< x 10)))) 5))
(run "not" ((jit (lambda (x) (not (< x 5)))) 7))
(run "strlen" ((jit (lambda (s) (strlen s))) "hello"))
(run "string?" ((jit (lambda (s) (string? s))) "hello"))
(run "concat" ((jit (lambda (a b) (concat a b))) "foo" "bar"))
(run "substr" ((jit (lambda (s) (substr s 1 3))) "hello"))
(run "toupper" ((jit (lambda (s) (toUpper s))) "hello"))
(run "poly" ((jit (lambda (x) (+ (* x x) (* 2 x) 1))) 3))
