(settings "JITLog" true)
(define _jit_id (lambda (x) x))
(define jit_substr3 (jit (lambda (s i n) (substr s i n))))
(assert ((jit (lambda (x) (and (> x 0) (< x 10)))) 15) false "jit: and (false)")
(assert ((jit (lambda (x) (or (< x 0) (> x 10)))) 15) true "jit: or (true)")
(assert ((jit (lambda (s) (substr s 1 3))) "hello") "ell" "jit: substr")
(assert (equal? (jit_substr3 "abcdef" 0 3) (substr "abcdef" 0 3)) true "jit substr3 parity prefix")
(assert (equal? (jit_substr3 "abcdef" 1 3) (substr "abcdef" 1 3)) true "jit substr3 parity middle")
(assert (equal? (jit_substr3 "abcdef" 3 0) (substr "abcdef" 3 0)) true "jit substr3 parity zero len")
(assert (equal? (jit_substr3 "abcdef" 3 3) (substr "abcdef" 3 3)) true "jit substr3 parity suffix")
(assert (equal? (jit_substr3 "abcdef" (+ 1 1) (+ 1 2)) (substr "abcdef" (+ 1 1) (+ 1 2))) true "jit substr3 parity arithmetic idx/len")
(assert (equal? (jit_substr3 (_jit_id 123456) 2 3) (substr (_jit_id 123456) 2 3)) true "jit substr3 parity String conversion from int")
(assert (equal? (jit_substr3 "abcdef" 1.0 3.0) (substr "abcdef" 1.0 3.0)) true "jit substr3 parity ToInt conversion from float")
(assert (equal? (jit_substr3 "äöüxyz" 0 6) (substr "äöüxyz" 0 6)) true "jit substr3 parity utf8 byte slicing")
