(print "A1")
((jit (lambda (a) a)) 5)
(print "A2")
((jit (lambda () 42)))
(print "A3")
((jit (lambda (a b) b)) 1 7)
(print "A4")
((jit (lambda (a b c) c)) 1 2 9)
(print "A5")
((jit (lambda (a b) a)) 3 4)
(print "A6")
((jit (lambda (a b c) b)) 1 8 3)
(print "A7")
(define jit_add_desc (jit (lambda (a b) (+ a b))))
(print "A8")
(strlike (serialize jit_add_desc) "(lambda %")
(print "A9")
(equal? (eval (list jit_add_desc 2 5)) 7)
(print "A10")
(equal? (apply jit_add_desc '(2 5)) 7)
(print "DONE")
