(settings "JITLog" false)
(print "start")
(define jit_add_desc (jit (lambda (a b) (+ a b))))
(print "eval jit_add_desc 2 5 => " (eval (list jit_add_desc 2 5)))
(print "apply jit_add_desc '(2 5) => " (apply jit_add_desc '(2 5)))
(print "jit x+1 4 => " ((jit (lambda (x) (+ x 1))) 4))
(print "jit a+b 3 4 => " ((jit (lambda (a b) (+ a b))) 3 4))
(print "jit (2+x) x=3 => " ((jit (lambda (x) (+ (strlen "ab") x))) (strlen "abc")))
(print "jit deep + 10 => " ((jit (lambda (x) (+ (+ (+ x 1) 2) 3))) 10))
(print "jit sql_abs -7 => " ((jit (lambda (x) (sql_abs x))) -7))
(print "jit sqrt 9 => " ((jit (lambda (x) (sqrt x))) 9))
(print "jit strlike world hello => " ((jit (lambda (s) (strlike s "hello"))) "world"))
