(print "U1")
((jit (lambda () (int? nil))))
(print "U2")
((jit (lambda () (int? true))))
(print "U3")
((jit (lambda () (int? false))))
(print "U4")
((jit (lambda () (int? "hello"))))
(print "U5")
((jit (lambda () (int? 3.14))))
(print "U6")
(define _jit_int? (jit (lambda (x) (int? x))))
(print "U7")
(_jit_int? nil)
(print "U8")
(_jit_int? true)
(print "U9")
(_jit_int? false)
(print "U10")
(_jit_int? 3.14)
(print "U11")
(_jit_int? "hello")
(print "U12")
(_jit_int? (size "abc"))
(print "U13")
(_jit_int? (* 2 3))
(print "U14")
(_jit_int? (+ (size "abc") (size "de")))
(print "U15")
(_jit_int? (* 0 1))
(print "U16")
(_jit_int? (* -1 42))
(print "U17")
((jit (lambda (x) (! (int? x)))) 3.14)
(print "U18")
((jit (lambda (x) (! (int? x)))) (size "a"))
(print "U19")
((jit (lambda () (nil? nil))))
(print "U20")
((jit (lambda () (nil? true))))
(print "U21")
((jit (lambda () (nil? 3.14))))
(print "U22")
((jit (lambda () (nil? "hi"))))
(print "U23")
(define _jit_nil? (jit (lambda (x) (nil? x))))
(print "U24")
(_jit_nil? nil)
(print "U25")
(_jit_nil? true)
(print "U26")
(_jit_nil? false)
(print "U27")
(_jit_nil? 3.14)
(print "U28")
(_jit_nil? "hello")
(print "U29")
(_jit_nil? (size "abc"))
(print "U30")
(_jit_nil? (* 2 3))
(print "U31")
(define _jit_number? (jit (lambda (x) (number? x))))
(print "U32")
(_jit_number? 42)
(print "U33")
(_jit_number? (size "abc"))
(print "U34")
(_jit_number? 3.14)
(print "U35")
(_jit_number? nil)
(print "U36")
(_jit_number? true)
(print "U37")
(_jit_number? "hello")
(print "U38")
(_jit_number? false)
(print "U39")
(define _jit_int_of_number (jit (lambda (x) (int? (number? x)))))
(print "U40")
(_jit_int_of_number 42)
(print "U41")
(_jit_int_of_number "hi")
(print "U42")
(define _jit_nil_of_nil (jit (lambda (x) (nil? (nil? x)))))
(print "U43")
(_jit_nil_of_nil nil)
(print "U44")
(_jit_nil_of_nil 42)
(print "U45")
(define _jit_number_of_number (jit (lambda (x) (number? (number? x)))))
(print "U46")
(_jit_number_of_number 42)
(print "U47")
(define _jit_nil_of_number (jit (lambda (x) (nil? (number? x)))))
(print "U48")
(_jit_nil_of_number 42)
(print "U49")
(_jit_nil_of_number "hi")
(print "U50")
(define _jit_int_of_nil (jit (lambda (x) (int? (nil? x)))))
(print "U51")
(_jit_int_of_nil nil)
(print "U52")
(_jit_int_of_nil 5)
(print "U53")
(define _jit_add2 (jit (lambda (a b) (+ a b))))
(print "U54")
(_jit_add2 3 4)
(print "U55")
(_jit_add2 -1 1)
(print "U56")
(_jit_add2 100 200)
(print "U57")
(define _jit_add3 (jit (lambda (a b c) (+ a b c))))
(print "U58")
(_jit_add3 1 2 3)
(print "U59")
(define _jit_sub2 (jit (lambda (a b) (- a b))))
(print "U60")
(_jit_sub2 10 3)
(print "U61")
(_jit_sub2 0 5)
(print "U62")
(define _jit_add_if (jit (lambda (a b) (+ a b))))
(print "U63")
(_jit_add_if 1 2.5)
(print "U64")
(_jit_add_if 2.5 3.5)
(print "U65")
(define _jit_add3m (jit (lambda (a b c) (+ a b c))))
(print "U66")
(_jit_add3m 1 2 3.0)
(print "U67")
(_jit_add3m 1.0 2 3)
(print "U68")
(_jit_add3m 1 nil 3)
(print "U69")
(define _jit_add4m (jit (lambda (a b c d) (+ a b c d))))
(print "U70")
(_jit_add4m 1 2 3 4)
(print "U71")
(_jit_add4m 1 2 3.0 4)
(print "U72")
(_jit_add4m 1 2 nil 4)
(print "U73")
(define _jit_x2p2 (jit (lambda (x) (+ (* x 2) 2))))
(print "U74")
(_jit_x2p2 5)
(print "U75")
(_jit_x2p2 0)
(print "U76")
(_jit_x2p2 -3)
(print "DONE")
