(settings "LogJIT" true)
(print "=== add test ===")
(define jit_add (jit (lambda (a b) (+ a b))))
(print "add compiled:" (jit? jit_add))
(print "add 3 4 =" (jit_add 3 4))
(print "=== mul test ===")
(define jit_mul (jit (lambda (a b) (* a b))))
(print "mul compiled:" (jit? jit_mul))
(if (jit? jit_mul)
  (print "mul 3 4 =" (jit_mul 3 4))
  (print "mul NOT compiled"))
