(print "T1")
((jit (lambda (a b c d) (+ (* a d) (* b c)))) 2 3 4 5)
(print "T2")
((jit (lambda (a b c d) (- (* a b) (* c d)))) 5 4 3 2)
(print "T3")
((jit (lambda (a b c d) (* (+ a b) (+ c d)))) 1 2 3 4)
(print "T4")
((jit (lambda (x) (if (> (* x x) 10) (* x 2) (+ x 1)))) 4)
(print "T5")
((jit (lambda (x) (if (> (* x x) 10) (* x 2) (+ x 1)))) 2)
(print "T6")
((jit (lambda (a b) (if (> (+ a b) 10) (* a b) (+ a b)))) 7 5)
(print "T7")
((jit (lambda (a b) (if (> (+ a b) 10) (* a b) (+ a b)))) 3 4)
(print "T8")
((jit (lambda (x) (and (> (* x 2) 5) (< (* x 3) 20)))) 3)
(print "T9")
((jit (lambda (x) (and (> (* x 2) 5) (< (* x 3) 20)))) 7)
(print "T10")
((jit (lambda (x) (or (< x 0) (> (* x x) 100)))) 11)
(print "DONE")
