(print "M1")
((jit (lambda (a) a)) 5)
(print "M2")
((jit (lambda () 42)))
(print "M3")
((jit (lambda (a b) b)) 1 7)
(print "M4")
((jit (lambda (a b c) c)) 1 2 9)
(print "M5")
((jit (lambda (x) (+ x 1))) 4)
(print "M6")
((jit (lambda (x) (- x 3))) 10)
(print "M7")
((jit (lambda (x) (* x 2))) 5)
(print "M8")
((jit (lambda (a b) (+ a b))) 3 4)
(print "M9")
((jit (lambda (a b) (* a b))) 3 4)
(print "M10")
((jit (lambda (a b) (- a b))) 10 3)
(print "M11")
((jit (lambda (x) (* (+ x 1) 2))) 4)
(print "M12")
((jit (lambda (x) (+ (* x 2) 1))) 4)
(print "M13")
((jit (lambda (a b c) (+ (* a b) c))) 3 4 5)
(print "M14")
((jit (lambda (a b c d) (+ (* a b) (* c d)))) 2 3 4 5)
(print "M15")
((jit (lambda (x) (+ (+ (+ x 1) 2) 3))) 10)
(print "M16")
((jit (lambda (x) (* (* (* x 2) 2) 2))) 3)
(print "M17")
((jit (lambda (a b) (- (* a a) (* b b)))) 5 3)
(print "M18")
((jit (lambda (a b c) (+ a (- b c)))) 10 7 3)
(print "M19")
((jit (lambda (x) (if (< x 5) 1 0))) 3)
(print "M20")
((jit (lambda (x) (if (< x 5) 1 0))) 7)
(print "M21")
((jit (lambda () (if true 1 2))))
(print "M22")
((jit (lambda () (or false true))))
(print "M23")
((jit (lambda () (and true true))))
(print "M24")
((jit (lambda (x) (and (> x 0) (< x 10)))) 5)
(print "M25")
((jit (lambda (x) (and (> x 0) (< x 10)))) 15)
(print "M26")
((jit (lambda (x) (or (< x 0) (> x 10)))) 5)
(print "M27")
((jit (lambda (x) (or (< x 0) (> x 10)))) 15)
(print "M28")
((jit (lambda (x) (not (< x 5)))) 3)
(print "M29")
((jit (lambda (x) (not (< x 5)))) 7)
(print "M30")
((jit (lambda (x) (! x))) true)
(print "M31")
((jit (lambda (x) (! x))) false)
(print "M32")
((jit (lambda (x) (floor x))) 3.9)
(print "M33")
((jit (lambda (x) (floor x))) -3.1)
(print "M34")
((jit (lambda (x) (ceil x))) 3.1)
(print "M35")
((jit (lambda (x) (ceil x))) -3.9)
(print "M36")
((jit (lambda (x) (sql_abs x))) -7)
(print "M37")
((jit (lambda (x) (sql_abs x))) -7.5)
(print "M38")
((jit (lambda (x) (sqrt x))) 9)
(print "M39")
((jit (lambda (x) (sqrt x))) -1)
(print "M40")
((jit (lambda (x) (list? x))) '(1 2 3))
(print "M41")
((jit (lambda (x) (list? x))) 42)
(print "M42")
((jit (lambda (s) (strlen s))) "hello")
(print "M43")
((jit (lambda (s) (string? s))) "hello")
(print "M44")
((jit (lambda (a b) (concat a b))) "foo" "bar")
(print "M45")
((jit (lambda (s) (substr s 1 3))) "hello")
(print "M46")
((jit (lambda (s) (toUpper s))) "hello")
(print "M47")
((jit (lambda (x) (+ (* x x) (* 2 x) 1))) 3)
(print "DONE")
