(settings "JITLog" false)
(define r1 ((jit (lambda (x) (floor x))) 3.9))
(print r1)
(print (int? r1))
(print (equal? r1 3.0))
(define r2 ((jit (lambda (x) (ceil x))) -3.9))
(print r2)
(print (int? r2))
(print (equal? r2 -3.0))
(define r3 ((jit (lambda (x) (sql_abs x))) -7))
(print r3)
(print (int? r3))
(print (equal? r3 7))
(define r4 ((jit (lambda (x) (sql_abs x))) -7.5))
(print r4)
(print (int? r4))
(print (equal? r4 7.5))
