(settings "JITLog" false)
(print ((jit (lambda (a) a)) 5))
(print ((jit (lambda () 42))))
(print ((jit (lambda (a b) b)) 1 7))
(print ((jit (lambda (a b c) c)) 1 2 9))
(print ((jit (lambda (a b) a)) 3 4))
(print ((jit (lambda (a b c) b)) 1 8 3))
(define jit_id_desc (jit (lambda (x) x)))
(print (jit? jit_id_desc))
(print (jit? (jit (lambda () 42))))
(define jit_add_desc (jit (lambda (a b) (+ a b))))
(print (serialize jit_add_desc))
(print (equal? (eval (list jit_add_desc 2 5)) 7))
(print (equal? (apply jit_add_desc '(2 5)) 7))
(print (jit? (lambda (a b) (+ a b))))
(define jit_fallback_desc (jit (lambda () (now))))
(print (jit? jit_fallback_desc))
(print (number? (jit_fallback_desc)))
