(settings "JITLog" false)
(print ((jit (lambda () (floor 1.9)))))
(print ((jit (lambda () (floor -1.1)))))
(print ((jit (lambda () (ceil 1.1)))))
(print ((jit (lambda () (ceil -1.9)))))
(print ((jit (lambda () (sql_abs -3)))))
(print ((jit (lambda () (sql_abs -3.5)))))
(print ((jit (lambda () (sqrt 9.0)))))
(print ((jit (lambda () (sqrt -1.0)))))
(print ((jit (lambda () (<= 3 3)))))
(print ((jit (lambda () (> 5 3)))))
(print ((jit (lambda () (>= 3 3)))))
(print ((jit (lambda () (> 2.5 1.5)))))
(print ((jit (lambda () (nil? (nil? nil))))))
(print ((jit (lambda () (nil? (nil? 42))))))
