(print "floor+")
(print ((jit (lambda (x) (floor x))) 3.7))
(print (floor 3.7))
(print "floor-")
(print ((jit (lambda (x) (floor x))) -3.7))
(print (floor -3.7))
(print "ceil+")
(print ((jit (lambda (x) (ceil x))) 3.2))
(print (ceil 3.2))
(print "ceil-")
(print ((jit (lambda (x) (ceil x))) -3.2))
(print (ceil -3.2))
(print "abs int")
(print ((jit (lambda (x) (sql_abs x))) -7))
(print (sql_abs -7))
(print "abs float")
(print ((jit (lambda (x) (sql_abs x))) -7.5))
(print (sql_abs -7.5))
(print "sqrt neg")
(print ((jit (lambda (x) (sqrt x))) -1))
(print (sqrt -1))
(print "cmp <=")
(print ((jit (lambda (a b) (<= a b))) 3 3))
(print (<= 3 3))
(print "cmp >")
(print ((jit (lambda (a b) (> a b))) 5 3))
(print (> 5 3))
(print "cmp >=")
(print ((jit (lambda (a b) (>= a b))) 3 3))
(print (>= 3 3))
(print "cmp float>")
(print ((jit (lambda (a b) (> a b))) 2.5 1.5))
(print (> 2.5 1.5))
(print "nil? bool false")
(print ((jit (lambda (x) (nil? x))) (nil? nil)))
(print (nil? (nil? nil)))
(print "nil? bool false2")
(print ((jit (lambda (x) (nil? x))) (nil? 42)))
(print (nil? (nil? 42)))
