(settings "JITLog" false)
(print ((jit (lambda (a b) (<= a b))) 3 3))
(print ((jit (lambda (a b) (> a b))) 5 3))
(print ((jit (lambda (a b) (>= a b))) 3 3))
(print ((jit (lambda (a b) (> a b))) 2.5 1.5))
