(settings "JITLog" false)
(print "b1") (print ((jit (lambda (s) (strlen s))) "hello"))
(print "b2") (print ((jit (lambda (a b) (concat a b))) "foo" "bar"))
(print "b3") (print ((jit (lambda (s) (substr s 1 3))) "hello"))
(print "b4") (define jit_substr3 (jit (lambda (s i n) (substr s i n))))
(print (jit_substr3 "abcdef" 0 3))
(print "b5") (print ((jit (lambda (x) (+ (* x x) (* 2 x) 1))) 3))
(print "b6") (print ((jit (lambda (x) (+ (* x x) (* 2 x) 1))) 5))
(print "b7") (print ((jit (lambda (a b c d) (+ (* a d) (* b c)))) 2 3 4 5))
(print "b8") (print ((jit (lambda (a b c d) (- (* a b) (* c d)))) 5 4 3 2))
(print "done")
