(settings "JITLog" true)
(print "floor+" ((jit (lambda (x) (floor x))) 3.7))
(print "floor-" ((jit (lambda (x) (floor x))) -3.7))
(print "ceil+" ((jit (lambda (x) (ceil x))) 3.2))
(print "ceil-" ((jit (lambda (x) (ceil x))) -3.2))
(print "absi" ((jit (lambda (x) (sql_abs x))) -7))
(print "absf" ((jit (lambda (x) (sql_abs x))) -7.5))
(print "sqrtneg" ((jit (lambda (x) (sqrt x))) -1))
(print "le" ((jit (lambda (a b) (<= a b))) 1 2))
(print "ge" ((jit (lambda (a b) (>= a b))) 2 1))
(print "nil1" ((jit (lambda () (nil? (nil? nil))))))
(print "nil2" ((jit (lambda () (nil? (nil? 42))))))
