(settings "JITLog" false)
(print "t1" ((jit (lambda (x) (+ x 1))) 4))
(print "t2" ((jit (lambda (x) (* x 2))) 5))
(print "t3" ((jit (lambda (x) (+ (strlen "ab") x))) (strlen "abc")))
(print "t4" ((jit (lambda (a b) (* a b))) 3 4))
(print "t5" ((jit (lambda (x) (* (+ x 1) 2))) 4))
(print "t6" ((jit (lambda (x) (+ (* x 2) 1))) 4))
(print "t7" ((jit (lambda (a b c) (+ (* a b) c))) 3 4 5))
(print "t8" ((jit (lambda (x) (+ (+ (+ x 1) 2) 3))) 10))
(print "t9" ((jit (lambda (x) (* (* (* x 2) 2) 2))) 3))
(print "t10" ((jit (lambda () (substr "abcdef" 2 3)))))
(print "t11" ((jit (lambda (x) (+ (* x x) (* 2 x) 1))) 5))
(print "t12" ((jit (lambda () (+ (* 5 5) 10 1)))))
(print "t13" ((jit (lambda (x) (* (+ x 1) (+ x 2)))) 3))
(print "t14" ((jit (lambda (x) (- (* 3 x x) (* 2 x))) ) 4))
(print "t15" ((jit (lambda (x) (* (+ x 1) (- x 1)))) 6))
(print "t16" ((jit (lambda (a b) (+ (* 3 a) (* 4 b)))) 2 5))
(print "t17" ((jit (lambda (x) (if (> (* x x) 10) (* 2 x) (+ x 1)))) 4))
(print "t18" ((jit (lambda (a b) (* a b))) 7 8))
(print "t19" ((jit (lambda () (+ 1 2.5)))))
(print "t20" ((jit (lambda () (+ 2.5 3.5)))))
(print "t21" ((jit (lambda () (+ (* 5 2) 2)))))
(print "t22" ((jit (lambda () (+ (* 0 2) 2)))))
(print "t23" ((jit (lambda () (+ (* -3 2) 2)))))
(print "done")
