(define jit_add_desc (jit (lambda (a b) (+ a b))))
(print "eval desc:" (eval (list jit_add_desc 2 5)))
(print "apply desc:" (apply jit_add_desc '(2 5)))
(print "a+b:" ((jit (lambda (a b) (+ a b))) 3 4))
(print "strlen+1:" ((jit (lambda (a) (+ (strlen a) 1))) "hello"))
(define _jit_id (lambda (x) x))
(define jit_substr3 (jit (lambda (s i n) (substr s i n))))
(print "sub prefix:" (jit_substr3 "abcdef" 0 3))
(print "sub middle:" (jit_substr3 "abcdef" 1 3))
(print "sub zero:" (jit_substr3 "abcdef" 3 0))
(print "sub suffix:" (jit_substr3 "abcdef" 3 3))
(print "sub arith:" (jit_substr3 "abcdef" (+ 1 1) (+ 1 2)))
(print "sub int->str:" (jit_substr3 (_jit_id 123456) 2 3))
(print "sub float->int:" (jit_substr3 "abcdef" 1.0 3.0))
(print "sub utf8:" (jit_substr3 "äöüxyz" 0 6))
(define _jit_add2 (jit (lambda (a b) (+ a b))))
(print "3+4:" (_jit_add2 3 4))
(print "-1+1:" (_jit_add2 -1 1))
(print "100+200:" (_jit_add2 100 200))
(define _jit_add_if (jit (lambda (a b) (+ a b))))
(print "1+2.5:" (_jit_add_if 1 2.5))
(print "2.5+3.5:" (_jit_add_if 2.5 3.5))
(exit)
