(print ((jit (lambda (x) (+ x 1))) 4))
(print ((jit (lambda (x) (* x 2))) 5))
(print ((jit (lambda (x) (+ (strlen "ab") x))) (strlen "abc")))
(print ((jit (lambda (a b) (* a b))) 3 4))
(print ((jit (lambda (x) (* (+ x 1) 2))) 4))
(print ((jit (lambda (x) (+ (* x 2) 1))) 4))
(print ((jit (lambda (a b c) (+ (* a b) c))) 3 4 5))
(print ((jit (lambda (x) (+ (+ (+ x 1) 2) 3))) 10))
(print ((jit (lambda (x) (* (* (* x 2) 2) 2))) 3))
(print ((jit (lambda (x) (substr "abcde" x 2))) 1))
(print ((jit (lambda (x) (+ (* x x) (* 2 x) 1))) 5))
(print ((jit (lambda () (+ (* 5 5) (* 2 5) 1)))))
(print ((jit (lambda (x) (* (+ x 1) (+ x 2)))) 3))
(print ((jit (lambda (x) (- (* 3 x x) (* 2 x)))) 4))
(print ((jit (lambda (x) (- (* (+ x 1) (- x 1)) 0))) 5))
(print ((jit (lambda (a b) (+ (* 3 a) (* 4 b)))) 2 5))
(print ((jit (lambda (x) (if (> (* x x) 10) (* 2 x) (+ x 1)))) 4))
(print ((jit (lambda (a b) (* a b))) 3 4))
(print ((jit (lambda () (+ 1 2.5)))))
(print ((jit (lambda () (+ 2.5 3.5)))))
(print ((jit (lambda () (+ (* 5 2) 2)))))
(print ((jit (lambda () (+ (* 0 2) 2)))))
(print ((jit (lambda () (+ (* -3 2) 2)))))
