(settings "JITLog" false)
(print (equal? ((jit (lambda (x) (floor x))) 3.9) 3.0))
(print (equal? ((jit (lambda (x) (floor x))) -3.9) -4.0))
(print (equal? ((jit (lambda (x) (ceil x))) 3.1) 4.0))
(print (equal? ((jit (lambda (x) (ceil x))) -3.9) -3.0))
(print (equal? ((jit (lambda (x) (sql_abs x))) -7) 7))
(print (equal? ((jit (lambda (x) (sql_abs x))) -7.5) 7.5))
(print (equal? ((jit (lambda (x) (sqrt x))) 9.0) 3.0))
(print (equal? ((jit (lambda (a b) (<= a b))) 3 3) true))
(print (equal? ((jit (lambda (a b) (> a b))) 5 3) true))
(print (equal? ((jit (lambda (a b) (>= a b))) 3 3) true))
(print (equal? ((jit (lambda (a b) (> a b))) 2.5 1.5) true))
(print (equal? ((jit (lambda () (nil? (nil? nil))))) false))
(print (equal? ((jit (lambda () (nil? (nil? 42))))) false))
