(settings "JITLog" false)
(define chk (lambda (x) (concat "x=" x)))
(chk ((jit (lambda (x) (+ x 1))) 4))
(chk ((jit (lambda (x) (- x 3))) 10))
(chk ((jit (lambda (x) (* x 2))) 5))
(chk ((jit (lambda (a b) (+ a b))) 3 4))
(chk ((jit (lambda (a b c) (+ a b c))) (strlen "a") (strlen "bb") (strlen "ccc")))
(chk ((jit (lambda (x) (+ (strlen "ab") x))) (strlen "abc")))
(chk ((jit (lambda (a b) (* a b))) 3 4))
(chk ((jit (lambda (a b) (- a b))) 10 3))
(chk ((jit (lambda (x) (* (+ x 1) 2))) 4))
(chk ((jit (lambda (x) (+ (* x 2) 1))) 4))
(chk ((jit (lambda (a b c) (+ (* a b) c))) 3 4 5))
(chk ((jit (lambda (a b c d) (+ (* a b) (* c d)))) 2 3 4 5))
(chk ((jit (lambda (x) (+ (+ (+ x 1) 2) 3))) 10))
(chk ((jit (lambda (x) (* (* (* x 2) 2) 2))) 3))
(chk ((jit (lambda (a b) (- (* a a) (* b b)))) 5 3))
(chk ((jit (lambda (a b c) (+ a (- b c)))) 10 7 3))
(print "ok")
