(settings "JITLog" false)
(print ((jit (lambda (x) (floor x))) 3.9))
(print ((jit (lambda (x) (floor x))) -3.9))
(print ((jit (lambda (x) (ceil x))) 3.1))
(print ((jit (lambda (x) (ceil x))) -3.9))
(print ((jit (lambda (x) (sql_abs x))) -7))
(print ((jit (lambda (x) (sql_abs x))) -7.5))
(print ((jit (lambda (x) (sqrt x))) 9.0))
(print ((jit (lambda (x) (sqrt x))) -1.0))
