(settings "JITLog" false)
(print "a1") (print ((jit (lambda (a) a)) 5))
(print "a2") (print ((jit (lambda () 42))))
(print "a3") (print ((jit (lambda (a b) b)) 1 7))
(print "a4") (print ((jit (lambda (x) (+ x 1))) 4))
(print "a5") (print ((jit (lambda (x) (- x 3))) 10))
(print "a6") (print ((jit (lambda (x) (* x 2))) 5))
(print "a7") (print ((jit (lambda (x) (and (> x 0) (< x 10)))) 5))
(print "a8") (print ((jit (lambda (x) (and (> x 0) (< x 10)))) 15))
(print "a9") (print ((jit (lambda (x) (or (< x 0) (> x 10)))) 5))
(print "a10") (print ((jit (lambda (x) (or (< x 0) (> x 10)))) 15))
(print "done")
