/* Copyright (C) 2026 Carl-Philip Hänsch
SPDX-License-Identifier: GPL-3.0-or-later */

/* SQL expression compilation returns (formula type collation). Collation is
(name coercibility), or nil for non-text results. Only value-producing operands
participate in type aggregation: CASE predicates and substring offsets do not.
Descriptors are resolved before relational rewrites; ORDER and comparisons use
canonical collate callbacks, and result descriptors survive in the IR context. */
(define sql_collation (lambda (value collation) value))
(define sql_collated_in (lambda (values value less)
	(if (nil? value) nil
		(reduce values (lambda (found candidate)
			(if (equal? found true) true
				(if (nil? candidate) nil
					(if (and (not (less value candidate)) (not (less candidate value))) true found)))) false))))

(define sql_cast_value (lambda (value type)
	(if (nil? value) nil
		(if (sql_text_type? type) (concat value)
			(if (equal? type "BIGINT") (intdiv (simplify value) 1) (simplify value))))))
(define sql_typed_value (lambda (value type collation) value))
(define sql_parameter_value (lambda (value type collation) value))
(define sql_info_formula car)
(define sql_info_type cadr)
(define sql_info_collation (lambda (info) (nth info 2)))
(define sql_info (lambda (formula type collation) (list formula type collation)))
(define sql_text_type? (lambda (type)
	(has? '("CHAR" "VARCHAR" "TEXT" "TINYTEXT" "MEDIUMTEXT" "LONGTEXT" "ENUM" "SET" "BINARY" "VARBINARY" "BLOB" "TINYBLOB" "MEDIUMBLOB" "LONGBLOB") type)))
(define sql_numeric_type? (lambda (type)
	(has? '("BOOL" "BOOLEAN" "INT" "INTEGER" "BIGINT" "SMALLINT" "TINYINT" "MEDIUMINT" "BIT" "DECIMAL" "NUMERIC" "FLOAT" "DOUBLE" "REAL") type)))
(define sql_collation_name (lambda (info)
	(if (nil? (sql_info_collation info)) "bin" (car (sql_info_collation info)))))

(define sql_merge_collation (lambda (a b)
	(if (nil? a) b (if (nil? b) a
		(if (equal? (car a) (car b)) (list (car a) (min (cadr a) (cadr b)))
			(if (< (cadr a) (cadr b)) a (if (> (cadr a) (cadr b)) b
				(if (equal? (cadr a) 0) (error "Illegal mix of explicit collations")
					(if (or (equal? (car a) "bin") (strlike (car a) "%_bin")) a
						(if (or (equal? (car b) "bin") (strlike (car b) "%_bin")) b
							(error "Illegal mix of collations")))))))))))

(define sql_merge_info (lambda (a b)
	(sql_info nil
		(if (equal? (sql_info_type a) "NULL") (sql_info_type b)
			(if (equal? (sql_info_type b) "NULL") (sql_info_type a)
				(if (equal? (sql_info_type a) (sql_info_type b)) (sql_info_type a)
					(if (or (sql_text_type? (sql_info_type a)) (sql_text_type? (sql_info_type b))) "VARCHAR"
						(if (or (equal? (sql_info_type a) "DOUBLE") (equal? (sql_info_type b) "DOUBLE")) "DOUBLE"
							(if (and (sql_numeric_type? (sql_info_type a)) (sql_numeric_type? (sql_info_type b))) "DECIMAL" "VARCHAR"))))))
		(sql_merge_collation (sql_info_collation a) (sql_info_collation b)))))
(define sql_merge_infos (lambda (infos)
	(reduce infos sql_merge_info (sql_info nil "NULL" nil))))

(define sql_source_column_info (lambda (src col)
	(if (source_is_base_table? src)
		(begin
			(define meta (find (get_schema (source_schema src) (source_relation src))
				(lambda (entry) (equal?? (entry "Field") col)) nil))
			(define type (toUpper (coalesceNil (if (nil? meta) nil (meta "RawType")) "UNKNOWN")))
			(sql_info nil type (if (sql_text_type? type)
				(list (coalesceNil (if (nil? meta) nil (meta "Collation")) "bin") 2) nil)))
		(begin
			(define fields (sql_query_result_infos (normalize_query_ast (source_relation src))))
			(coalesceNil (get_assoc fields col) (sql_info nil "VARCHAR" (list "bin" 2)))))))

(define sql_case_values (lambda (args)
	(match args
		'(last) (list last)
		(cons _condition (cons value rest)) (cons value (sql_case_values rest))
		_ '())))

/* Function objects in the SQL builtin registry retain their SQL return contract.
The parser may use named runtime operators or registered function values. */
(define sql_function_rule (lambda (head)
	(coalesceNil (find (sql_function_rules) (lambda (entry)
		(or (equal? head (car entry))
			(and (symbol? head) (equal? (string head) (string (car entry)))))) nil)
		(list head "VARCHAR" "default"))))

(define sql_expr_info (lambda (sources expr)
	(match expr
		((symbol get_column) alias _ic col _cic)
		(begin
			(define src (find sources (lambda (src) (or (nil? alias) (equal?? alias (source_alias src)))) nil))
			(define info (if (nil? src) (sql_info nil "VARCHAR" (list "bin" 2)) (sql_source_column_info src col)))
			(sql_info expr (sql_info_type info) (sql_info_collation info)))
		((symbol sql_collation) value collation)
		(begin
			(define info (sql_expr_info sources value))
			(sql_info (list (quote sql_collation) (car info) collation) (cadr info) (list collation 0)))
		((symbol sql_temporal_output) value type timezone)
		(sql_info (list (quote sql_temporal_output) (car (sql_expr_info sources value)) type timezone) type nil)
		((symbol sql_parameter_value) value type collation)
		(sql_info expr type (if (nil? collation) nil (list collation 4)))
		((symbol sql_typed_value) value type collation)
		(sql_info (list (quote sql_typed_value) (sql_info_formula (sql_expr_info sources value)) type collation) type
			(if (nil? collation) nil (list collation 2)))
		((symbol inner_select_exists) query)
		(sql_info (list (quote inner_select_exists) (sql_type_query query sources)) "BOOLEAN" nil)
		((symbol inner_select_in) probe query)
		(sql_info (list (quote inner_select_in) (car (sql_expr_info sources probe)) (sql_type_query query sources)) "BOOLEAN" nil)
		((symbol inner_select) query)
		(begin
			(define typed (sql_type_query query sources))
			(define infos (sql_query_result_infos typed))
			(define info (if (empty_list? infos) (sql_info nil "NULL" nil) (cadr infos)))
			(sql_info (list (quote inner_select) typed) (sql_info_type info) (sql_info_collation info)))
		((symbol window_func) name args spec)
		(begin
			(define infos (map args (lambda (arg) (sql_expr_info sources arg))))
			(define first (if (empty_list? infos) (sql_info nil "BIGINT" nil) (car infos)))
			(define type (if (has? '("ROW_NUMBER" "RANK" "DENSE_RANK" "COUNT" "NTILE") name) "BIGINT"
				(if (has? '("SUM" "AVG") name) "DECIMAL" (cadr first))))
			(define typed_spec (list (map (car spec) (lambda (key) (car (sql_expr_info sources key))))
				(map (cadr spec) (lambda (item) (begin
					(define info (sql_expr_info sources (car item)))
					(list (car info) (if (or (equal? (cadr item) <) (equal? (cadr item) >))
						(collate (sql_collation_name info) (equal? (cadr item) >)) (cadr item))))))))
			(sql_info (list (quote window_func) name (map infos car) typed_spec) type
				(if (sql_text_type? type) (sql_info_collation first) nil)))
		((symbol group_concat_distinct) value separator)
		(begin
			(define info (sql_expr_info sources value))
			(sql_info (list (quote aggregate) (car info) (quote sql_distinct_accumulate) (list (quote list))
				(list (quote lambda) (list (quote values))
					(list (quote reduce) (list (quote sql_distinct_values) (quote values) (collate (sql_collation_name info) false))
						(list (quote lambda) (list (quote acc) (quote value))
							(list (quote if) (list (quote nil?) (quote acc)) (list (quote concat) (quote value))
								(list (quote concat) (quote acc) separator (quote value)))) nil)))
				"VARCHAR" (sql_info_collation info)))
		((symbol count_distinct) value)
		(begin
			(define info (sql_expr_info sources value))
			(sql_info (list (quote aggregate) (car info) (quote sql_distinct_accumulate) (list (quote list))
				(list (quote lambda) (list (quote values))
					(list (quote count) (list (quote sql_distinct_values) (quote values) (collate (sql_collation_name info) false)))))
				"BIGINT" nil))
		((symbol aggregate) value reducer neutral)
		(begin
			(define info (sql_expr_info sources value))
			(define preserve (or (equal? reducer min) (equal? reducer max) (equal? reducer (quote min)) (equal? reducer (quote max))))
			(define typed_reducer (if (and preserve (sql_text_type? (cadr info)))
				(list (quote lambda) (list (quote left) (quote right))
					(list (quote if) (list (quote nil?) (quote left)) (quote right)
						(list (quote nil?) (quote right)) (quote left)
						(list (collate (sql_collation_name info) (or (equal? reducer max) (equal? reducer (quote max)))) (quote left) (quote right))
						(quote left) (quote right))) reducer))
			(sql_info (list (quote aggregate) (car info) typed_reducer neutral)
				(if preserve (cadr info) (if (and (equal? value 1) (equal? neutral 0)) "BIGINT"
					(if (sql_text_type? (cadr info)) "VARCHAR" "DECIMAL")))
				(if (or preserve (sql_text_type? (cadr info))) (sql_info_collation info) nil)))
		((symbol sql_in) values value)
		(begin
			(define input (sql_expr_info sources value))
			(define infos (map (cdr values) (lambda (item) (sql_expr_info sources item))))
			(if (and (sql_text_type? (cadr input))
				(reduce infos (lambda (ok info) (and ok (or (equal? (cadr info) "NULL") (sql_text_type? (cadr info))))) true))
				(sql_info (list (quote sql_collated_in) (cons (car values) (map infos car)) (car input)
					(collate (sql_collation_name (sql_merge_infos (cons input infos))) false)) "BOOLEAN" nil)
				(sql_info (list (quote sql_in) (cons (car values) (map infos car)) (car input)) "BOOLEAN" nil)))
		((symbol strlike) value pattern collation)
		(begin
			(define input (sql_expr_info sources value))
			(sql_info (list (quote strlike) (car input) (car (sql_expr_info sources pattern))
				(if (nil? (sql_info_collation input)) collation (sql_collation_name input))) "BOOLEAN" nil))
		((symbol quote) value) (sql_info expr "VARCHAR" nil)
		((symbol lambda) _params _body) (sql_info expr "VARCHAR" nil)
		((symbol aggregate) value reducer neutral finalize)
		(begin
			(define info (sql_expr_info sources (list (quote aggregate) value reducer neutral)))
			(define result (sql_expr_info sources (if (and (list? finalize) (equal? (car finalize) (quote lambda)))
				(nth finalize 2) (list finalize nil))))
			(sql_info (list (quote aggregate) (cadr (car info)) reducer neutral finalize) (cadr result) (sql_info_collation result)))
		(cons head args)
		(begin
			(define infos (map args (lambda (arg) (sql_expr_info sources arg))))
			(define formula (cons head (map infos car)))
			(define rule (sql_function_rule head))
			(define mode (nth rule 2))
			(define values (if (equal? mode "case") (sql_case_values infos)
				(if (equal? mode "first") (slice infos 0 (min 1 (count infos))) infos)))
			(define combined (if (has? '("case" "first" "merge" "text") mode) (sql_merge_infos values) (sql_info nil (cadr rule) nil)))
			(define type (if (has? '("case" "merge") mode) (sql_info_type combined) (cadr rule)))
			(define collation (if (sql_text_type? type)
				(coalesceNil (sql_info_collation combined) (list "utf8mb4_unicode_520_ci" 4)) nil))
			(define coerced (if (and (has? '("case" "merge") mode) (sql_text_type? type)
				(reduce values (lambda (needed info) (or needed (sql_numeric_type? (cadr info)))) false))
				(if (equal? mode "case")
					(cons head (sql_coerce_case_args infos type))
					(cons head (map infos (lambda (info) (sql_coerce_info info type))))) formula))
			(sql_info (sql_compile_comparison head infos coerced) type collation))
		_ (sql_info expr
			(if (nil? expr) "NULL" (if (string? expr) "VARCHAR" (if (number? expr) (if (equal? expr (floor expr)) "BIGINT" "DOUBLE") (if (or (equal? expr true) (equal? expr false)) "BOOLEAN" "VARCHAR"))))
			(if (string? expr) (list "utf8mb4_unicode_520_ci" 4) nil)))))

/* SQL NULL handling surrounds the canonical Less relation. The compiler emits
this named scalar primitive so physical scan lowering can also derive bounds. */
(define sql_compare (lambda (left right less operator collation)
	(if (or (nil? left) (nil? right)) nil
		(match operator
			"equal??" (and (not (less left right)) (not (less right left)))
			"<" (less left right)
			">" (less right left)
			"<=" (not (less right left))
			">=" (not (less left right))
			_ (error "unsupported SQL comparison")))))

(define sql_compile_comparison (lambda (head infos formula)
	(if (and (has? (list (quote equal??) (quote <) (quote >) (quote <=) (quote >=)) head) (equal? (count infos) 2)
		(and (sql_text_type? (cadr (car infos))) (sql_text_type? (cadr (cadr infos)))))
		(list (quote sql_compare) (car (car infos)) (car (cadr infos))
			(collate (sql_collation_name (sql_merge_infos infos)) false) (string head)
			(sql_collation_name (sql_merge_infos infos)))
		formula)))

(define sql_merge_result_infos (lambda (left right)
	(match left
		(cons title (cons info rest)) (match right
			(cons _title (cons other remaining))
			(cons title (cons (sql_merge_info info other) (sql_merge_result_infos rest remaining)))
			_ (error "UNION branch column count mismatch"))
		_ (if (empty_list? right) '() (error "UNION branch column count mismatch")))))

(define sql_query_result_infos (lambda (query)
	(if (query_block? query)
		(coalesceNil (qassoc_get (qb_facts query) (quote result-types) nil)
			(map_assoc (expand_query_block_fields (qb_sources query) (qb_fields query))
				(lambda (_title expr) (sql_expr_info (qb_sources query) expr))))
		(if (union_block? query)
			(coalesceNil (qassoc_get (union_facts query) (quote result-types) nil) '()) '()))))

(define sql_type_query (lambda (query outer_sources)
	(if (query_block? query)
		(begin
			(define sources (map (qb_sources query) (lambda (src)
				(source_with_relation src (sql_type_query (source_relation src) outer_sources)))))
			(define all_sources (merge (list sources outer_sources)))
			(define compile (lambda (expr) (sql_expr_info all_sources expr)))
			(define fields (map_assoc (expand_query_block_fields sources (qb_fields query)) (lambda (_title expr) (compile expr))))
			(make_query_block (qb_schema query)
				(map sources (lambda (src) (source_with_join_expr src (car (compile (source_join_expr src))))))
				(map_assoc fields (lambda (_title info) (car info)))
				(car (compile (qb_where query)))
				(map (qb_group query) (lambda (expr) (car (compile expr))))
				(car (compile (qb_having query)))
				(map (coalesceNil (qb_order query) '()) (lambda (item) (begin
					(define info (compile (car item)))
					(list (car info) (if (or (equal? (cadr item) <) (equal? (cadr item) >))
						(collate (sql_collation_name info) (equal? (cadr item) >)) (cadr item))))))
				(qb_limit query) (qb_offset query) (qb_hidden query) (qb_stages query)
				(qassoc_set (qb_facts query) (quote result-types)
					(map_assoc fields (lambda (_title info) (sql_info nil (cadr info) (sql_info_collation info)))))))
		(if (union_block? query)
			(begin
				(define branches (map (union_branches query) (lambda (branch) (sql_type_query branch outer_sources))))
				(define fields (if (empty_list? branches) '() (sql_query_result_infos (car branches))))
				(define merged (reduce (cdr branches) (lambda (fields branch)
					(sql_merge_result_infos fields (sql_query_result_infos branch))) fields))
				(make_union_block (union_mode query) (map branches (lambda (branch) (sql_union_coerce_branch branch merged))) (union_order query) (union_limit query) (union_offset query)
					(qassoc_set (union_facts query) (quote result-types) merged)))
			query))))

(define sql_core_function_rules (list
	(list (quote sql_compare) "BOOLEAN" "fixed")
	(list (quote sql_collated_in) "BOOLEAN" "fixed")
	(list (quote json_arrayagg_finalize) "VARCHAR" "fixed")
	(list (quote json_objectagg_entry) "VARCHAR" "fixed")
	(list (quote json_value) "VARCHAR" "fixed")
	(list (quote count) "BIGINT" "fixed")
	(list (quote format_date) "VARCHAR" "fixed")
	(list (quote extract_date) "BIGINT" "fixed")
	(list (quote if) "NULL" "case")
	(list if "NULL" "case")
	(list (quote coalesceNil) "NULL" "merge")
	(list coalesceNil "NULL" "merge")
	(list (quote coalesce) "NULL" "merge")
	(list coalesce "NULL" "merge")
	(list (quote min) "NULL" "merge")
	(list min "NULL" "merge")
	(list (quote max) "NULL" "merge")
	(list max "NULL" "merge")
	(list (quote sql_concat) "VARCHAR" "text")
	(list sql_concat "VARCHAR" "text")
	(list (quote concat) "VARCHAR" "text")
	(list concat "VARCHAR" "text")
	(list (quote sql_substr) "VARCHAR" "first")
	(list sql_substr "VARCHAR" "first")
	(list (quote sql_trim) "VARCHAR" "first")
	(list sql_trim "VARCHAR" "first")
	(list (quote sql_ltrim) "VARCHAR" "first")
	(list sql_ltrim "VARCHAR" "first")
	(list (quote sql_rtrim) "VARCHAR" "first")
	(list sql_rtrim "VARCHAR" "first")
	(list (quote toUpper) "VARCHAR" "first")
	(list toUpper "VARCHAR" "first")
	(list (quote toLower) "VARCHAR" "first")
	(list toLower "VARCHAR" "first")
	(list (quote replace) "VARCHAR" "first")
	(list replace "VARCHAR" "first")
	(list (quote substr) "VARCHAR" "first")
	(list substr "VARCHAR" "first")
	(list (quote string_repeat) "VARCHAR" "first")
	(list string_repeat "VARCHAR" "first")
	(list (quote simplify) "DOUBLE" "fixed")
	(list simplify "DOUBLE" "fixed")
	(list (quote +) "DOUBLE" "fixed")
	(list + "DOUBLE" "fixed")
	(list (quote -) "DOUBLE" "fixed")
	(list - "DOUBLE" "fixed")
	(list (quote *) "DOUBLE" "fixed")
	(list * "DOUBLE" "fixed")
	(list (quote /) "DOUBLE" "fixed")
	(list / "DOUBLE" "fixed")
	(list (quote floor) "DOUBLE" "fixed")
	(list floor "DOUBLE" "fixed")
	(list (quote ceil) "DOUBLE" "fixed")
	(list ceil "DOUBLE" "fixed")
	(list (quote round) "DOUBLE" "fixed")
	(list round "DOUBLE" "fixed")
	(list (quote sqrt) "DOUBLE" "fixed")
	(list sqrt "DOUBLE" "fixed")
	(list (quote sql_abs) "DOUBLE" "fixed")
	(list sql_abs "DOUBLE" "fixed")
	(list (quote sql_rand) "DOUBLE" "fixed")
	(list sql_rand "DOUBLE" "fixed")
	(list (quote strlen) "BIGINT" "fixed")
	(list strlen "BIGINT" "fixed")
	(list (quote intdiv) "BIGINT" "fixed")
	(list intdiv "BIGINT" "fixed")
	(list (quote count_distinct) "BIGINT" "fixed")
	(list count_distinct "BIGINT" "fixed")
	(list (quote connection_id) "BIGINT" "fixed")
	(list connection_id "BIGINT" "fixed")
	(list (quote datediff) "BIGINT" "fixed")
	(list datediff "BIGINT" "fixed")
	(list (quote timestampdiff) "BIGINT" "fixed")
	(list timestampdiff "BIGINT" "fixed")
	(list (quote equal??) "BOOLEAN" "fixed")
	(list equal?? "BOOLEAN" "fixed")
	(list (quote equal?) "BOOLEAN" "fixed")
	(list equal? "BOOLEAN" "fixed")
	(list (quote <) "BOOLEAN" "fixed")
	(list < "BOOLEAN" "fixed")
	(list (quote >) "BOOLEAN" "fixed")
	(list > "BOOLEAN" "fixed")
	(list (quote <=) "BOOLEAN" "fixed")
	(list <= "BOOLEAN" "fixed")
	(list (quote >=) "BOOLEAN" "fixed")
	(list >= "BOOLEAN" "fixed")
	(list (quote sql_not) "BOOLEAN" "fixed")
	(list sql_not "BOOLEAN" "fixed")
	(list (quote not) "BOOLEAN" "fixed")
	(list not "BOOLEAN" "fixed")
	(list (quote nil?) "BOOLEAN" "fixed")
	(list nil? "BOOLEAN" "fixed")
	(list (quote and) "BOOLEAN" "fixed")
	(list and "BOOLEAN" "fixed")
	(list (quote or) "BOOLEAN" "fixed")
	(list or "BOOLEAN" "fixed")
	(list (quote strlike) "BOOLEAN" "fixed")
	(list strlike "BOOLEAN" "fixed")
	(list (quote equal_collate) "BOOLEAN" "fixed")
	(list equal_collate "BOOLEAN" "fixed")
	(list (quote notequal_collate) "BOOLEAN" "fixed")
	(list notequal_collate "BOOLEAN" "fixed")
	(list (quote now) "TIMESTAMP" "fixed")
	(list now "TIMESTAMP" "fixed")
	(list (quote current_date) "DATE" "fixed")
	(list current_date "DATE" "fixed")
	(list (quote date_trunc_day) "DATE" "fixed")
	(list date_trunc_day "DATE" "fixed")
	(list (quote from_unixtime) "DATETIME" "fixed")
	(list from_unixtime "DATETIME" "fixed")
	(list (quote sql_temporal_output) "VARCHAR" "fixed")
	(list sql_temporal_output "VARCHAR" "fixed")
	(list (quote sql_avg_divide) "DECIMAL" "fixed")
))

(define sql_cached_function_rules (once (lambda ()
	(merge (list sql_core_function_rules (list
		(list (sql_builtins "ABS") "DOUBLE" "fixed")
		(list (sql_builtins "ARRAY_TO_JSON") "VARCHAR" "fixed")
		(list (sql_builtins "CEIL") "DOUBLE" "fixed")
		(list (sql_builtins "CEILING") "DOUBLE" "fixed")
		(list (sql_builtins "CHARACTER_LENGTH") "BIGINT" "fixed")
		(list (sql_builtins "CHAR_LENGTH") "BIGINT" "fixed")
		(list (sql_builtins "CLOCK_TIMESTAMP") "TIMESTAMP" "fixed")
		(list (sql_builtins "CONNECTION_ID") "BIGINT" "fixed")
		(list (sql_builtins "CONVERT_TZ") "DATETIME" "fixed")
		(list (sql_builtins "CURRENT_DATE") "DATE" "fixed")
		(list (sql_builtins "CURRENT_TIMESTAMP") "TIMESTAMP" "fixed")
		(list (sql_builtins "CURRENT_USER") "VARCHAR" "fixed")
		(list (sql_builtins "DATABASE") "VARCHAR" "fixed")
		(list (sql_builtins "DATE") "DATE" "fixed")
		(list (sql_builtins "DATEDIFF") "BIGINT" "fixed")
		(list (sql_builtins "DATE_FORMAT") "VARCHAR" "fixed")
		(list (sql_builtins "DAY") "BIGINT" "fixed")
		(list (sql_builtins "DAYOFMONTH") "BIGINT" "fixed")
		(list (sql_builtins "DAYOFWEEK") "BIGINT" "fixed")
		(list (sql_builtins "FLOOR") "DOUBLE" "fixed")
		(list (sql_builtins "FROM_UNIXTIME") "DATETIME" "fixed")
		(list (sql_builtins "GREATEST") "VARCHAR" "merge")
		(list (sql_builtins "HOUR") "BIGINT" "fixed")
		(list (sql_builtins "ISNULL") "BIGINT" "fixed")
		(list (sql_builtins "JSONB_ARRAY_LENGTH") "BIGINT" "fixed")
		(list (sql_builtins "JSONB_BUILD_ARRAY") "VARCHAR" "fixed")
		(list (sql_builtins "JSONB_BUILD_OBJECT") "VARCHAR" "fixed")
		(list (sql_builtins "JSONB_EXTRACT_PATH") "VARCHAR" "fixed")
		(list (sql_builtins "JSONB_EXTRACT_PATH_TEXT") "VARCHAR" "fixed")
		(list (sql_builtins "JSONB_INSERT") "VARCHAR" "fixed")
		(list (sql_builtins "JSONB_OBJECT") "VARCHAR" "fixed")
		(list (sql_builtins "JSONB_PATH_EXISTS") "VARCHAR" "fixed")
		(list (sql_builtins "JSONB_PATH_EXISTS_TZ") "VARCHAR" "fixed")
		(list (sql_builtins "JSONB_PATH_MATCH") "VARCHAR" "fixed")
		(list (sql_builtins "JSONB_PATH_MATCH_TZ") "VARCHAR" "fixed")
		(list (sql_builtins "JSONB_PATH_QUERY_ARRAY") "VARCHAR" "fixed")
		(list (sql_builtins "JSONB_PATH_QUERY_ARRAY_TZ") "VARCHAR" "fixed")
		(list (sql_builtins "JSONB_PATH_QUERY_FIRST") "VARCHAR" "fixed")
		(list (sql_builtins "JSONB_PATH_QUERY_FIRST_TZ") "VARCHAR" "fixed")
		(list (sql_builtins "JSONB_POPULATE_RECORD_VALID") "VARCHAR" "fixed")
		(list (sql_builtins "JSONB_PRETTY") "VARCHAR" "fixed")
		(list (sql_builtins "JSONB_SET") "VARCHAR" "fixed")
		(list (sql_builtins "JSONB_SET_LAX") "VARCHAR" "fixed")
		(list (sql_builtins "JSONB_STRIP_NULLS") "VARCHAR" "fixed")
		(list (sql_builtins "JSONB_TYPEOF") "VARCHAR" "fixed")
		(list (sql_builtins "JSON_ARRAY") "VARCHAR" "fixed")
		(list (sql_builtins "JSON_ARRAY_APPEND") "VARCHAR" "fixed")
		(list (sql_builtins "JSON_ARRAY_INSERT") "VARCHAR" "fixed")
		(list (sql_builtins "JSON_ARRAY_LENGTH") "BIGINT" "fixed")
		(list (sql_builtins "JSON_BUILD_ARRAY") "VARCHAR" "fixed")
		(list (sql_builtins "JSON_BUILD_OBJECT") "VARCHAR" "fixed")
		(list (sql_builtins "JSON_CONTAINS") "BIGINT" "fixed")
		(list (sql_builtins "JSON_CONTAINS_PATH") "BIGINT" "fixed")
		(list (sql_builtins "JSON_DEPTH") "BIGINT" "fixed")
		(list (sql_builtins "JSON_EXTRACT") "VARCHAR" "fixed")
		(list (sql_builtins "JSON_EXTRACT_PATH") "VARCHAR" "fixed")
		(list (sql_builtins "JSON_EXTRACT_PATH_TEXT") "VARCHAR" "fixed")
		(list (sql_builtins "JSON_INSERT") "VARCHAR" "fixed")
		(list (sql_builtins "JSON_KEYS") "VARCHAR" "fixed")
		(list (sql_builtins "JSON_LENGTH") "BIGINT" "fixed")
		(list (sql_builtins "JSON_MERGE") "VARCHAR" "fixed")
		(list (sql_builtins "JSON_MERGE_PATCH") "VARCHAR" "fixed")
		(list (sql_builtins "JSON_MERGE_PRESERVE") "VARCHAR" "fixed")
		(list (sql_builtins "JSON_OBJECT") "VARCHAR" "fixed")
		(list (sql_builtins "JSON_OVERLAPS") "BIGINT" "fixed")
		(list (sql_builtins "JSON_PRETTY") "VARCHAR" "fixed")
		(list (sql_builtins "JSON_QUOTE") "VARCHAR" "fixed")
		(list (sql_builtins "JSON_REMOVE") "VARCHAR" "fixed")
		(list (sql_builtins "JSON_REPLACE") "VARCHAR" "fixed")
		(list (sql_builtins "JSON_SCALAR") "VARCHAR" "fixed")
		(list (sql_builtins "JSON_SCHEMA_VALID") "BIGINT" "fixed")
		(list (sql_builtins "JSON_SCHEMA_VALIDATION_REPORT") "VARCHAR" "fixed")
		(list (sql_builtins "JSON_SEARCH") "VARCHAR" "fixed")
		(list (sql_builtins "JSON_SET") "VARCHAR" "fixed")
		(list (sql_builtins "JSON_STORAGE_FREE") "BIGINT" "fixed")
		(list (sql_builtins "JSON_STORAGE_SIZE") "BIGINT" "fixed")
		(list (sql_builtins "JSON_STRIP_NULLS") "VARCHAR" "fixed")
		(list (sql_builtins "JSON_TYPE") "VARCHAR" "fixed")
		(list (sql_builtins "JSON_TYPEOF") "VARCHAR" "fixed")
		(list (sql_builtins "JSON_UNQUOTE") "VARCHAR" "fixed")
		(list (sql_builtins "JSON_VALID") "BIGINT" "fixed")
		(list (sql_builtins "JSON_VALUE") "VARCHAR" "fixed")
		(list (sql_builtins "KILL_QUERY") "VARCHAR" "fixed")
		(list (sql_builtins "LEAST") "VARCHAR" "merge")
		(list (sql_builtins "LENGTH") "BIGINT" "fixed")
		(list (sql_builtins "LOWER") "VARCHAR" "first")
		(list (sql_builtins "MINUTE") "BIGINT" "fixed")
		(list (sql_builtins "MONTH") "BIGINT" "fixed")
		(list (sql_builtins "NOW") "TIMESTAMP" "fixed")
		(list (sql_builtins "PASSWORD") "VARCHAR" "fixed")
		(list (sql_builtins "QUARTER") "BIGINT" "fixed")
		(list (sql_builtins "RAND") "DOUBLE" "fixed")
		(list (sql_builtins "RANDOM") "DOUBLE" "fixed")
		(list (sql_builtins "REGEXP_REPLACE") "VARCHAR" "first")
		(list (sql_builtins "REGEXP_SUBSTR") "VARCHAR" "first")
		(list (sql_builtins "REPEAT") "VARCHAR" "first")
		(list (sql_builtins "REPLACE") "VARCHAR" "first")
		(list (sql_builtins "ROUND") "DOUBLE" "fixed")
		(list (sql_builtins "ROW_TO_JSON") "VARCHAR" "fixed")
		(list (sql_builtins "SECOND") "BIGINT" "fixed")
		(list (sql_builtins "SESSION_USER") "VARCHAR" "fixed")
		(list (sql_builtins "SOUNDEX") "VARCHAR" "fixed")
		(list (sql_builtins "SQRT") "DOUBLE" "fixed")
		(list (sql_builtins "STRING_TO_VECTOR") "VARCHAR" "fixed")
		(list (sql_builtins "STR_TO_DATE") "DATETIME" "fixed")
		(list (sql_builtins "SUBSTR") "VARCHAR" "first")
		(list (sql_builtins "SUBSTRING") "VARCHAR" "first")
		(list (sql_builtins "SYSDATE") "DATETIME" "fixed")
		(list (sql_builtins "TIMESTAMPDIFF") "BIGINT" "fixed")
		(list (sql_builtins "TO_JSON") "VARCHAR" "fixed")
		(list (sql_builtins "TO_JSONB") "VARCHAR" "fixed")
		(list (sql_builtins "TO_TIMESTAMP") "DATETIME" "fixed")
		(list (sql_builtins "TRANSACTION_TIMESTAMP") "TIMESTAMP" "fixed")
		(list (sql_builtins "UNIX_TIMESTAMP") "BIGINT" "fixed")
		(list (sql_builtins "UPPER") "VARCHAR" "first")
		(list (sql_builtins "USER") "VARCHAR" "fixed")
		(list (sql_builtins "UTC_DATE") "DATE" "fixed")
		(list (sql_builtins "UTC_TIME") "TIME" "fixed")
		(list (sql_builtins "UTC_TIMESTAMP") "TIMESTAMP" "fixed")
		(list (sql_builtins "VECTOR_DIM") "VARCHAR" "fixed")
		(list (sql_builtins "VECTOR_DISTANCE") "DOUBLE" "fixed")
		(list (sql_builtins "VECTOR_TO_STRING") "VARCHAR" "fixed")
		(list (sql_builtins "WEEK") "BIGINT" "fixed")
		(list (sql_builtins "WEEKDAY") "BIGINT" "fixed")
		(list (sql_builtins "YEAR") "BIGINT" "fixed")
		(list (sql_builtins "YEARWEEK") "BIGINT" "fixed")
		(list (sql_builtins "SQL_NULL") "NULL" "fixed")
))))))

(define sql_function_rules (lambda ()
	(if (or (nil? sql_builtins) (symbol? sql_builtins)) sql_core_function_rules (sql_cached_function_rules))))

/* Group raw spellings within each shard first, then merge collation-equivalent
keys in one sorted batch. The existing Less factory remains the only authority;
no lowercasing, accent stripping or alternate equality is introduced. */
(define sql_tuple_less (lambda (left right relations)
	(match relations
		(cons less rest) (begin
			(define a (car left))
			(define b (car right))
			(if (and (nil? a) (nil? b)) (sql_tuple_less (cdr left) (cdr right) rest)
				(if (nil? a) true (if (nil? b) false
					(if (less a b) true (if (less b a) false
						(sql_tuple_less (cdr left) (cdr right) rest)))))))
		_ false)))

(define sql_merge_collated_groups (lambda (groups relations combine)
	(begin
		(define ordered (sort (extract_assoc groups (lambda (key payload) (list key payload)))
			(lambda (a b) (sql_tuple_less (car a) (car b) relations))))
		(define merged (reduce ordered (lambda (acc pair)
			(if (empty_list? acc) (list pair)
				(if (or (sql_tuple_less (car (car acc)) (car pair) relations)
					(sql_tuple_less (car pair) (car (car acc)) relations))
					(cons pair acc)
					(cons (list (car (car acc)) (combine (cadr (car acc)) (cadr pair))) (cdr acc))))) '()))
		(merge (reverse merged)))))

(define sql_distinct_accumulate (lambda (a b)
	(merge_unique (list (if (list? a) a (if (nil? a) '() (list a)))
		(if (list? b) b (if (nil? b) '() (list b)))))))
(define sql_distinct_values (lambda (values less)
	(map (extract_assoc
		(sql_merge_collated_groups
			(merge (map (filter values (lambda (value) (not (nil? value))))
				(lambda (value) (list (list value) true))))
			(list less) (lambda (a b) true))
		(lambda (key _value) key)) car)))

(define sql_group_equal (lambda (left right less)
	(if (nil? left) (nil? right) (if (nil? right) false
		(and (not (less left right)) (not (less right left)))))))

(define sql_coerce_info (lambda (info type)
	(if (or (equal? (cadr info) type) (equal? (cadr info) "NULL")) (car info)
		(list (quote sql_cast_value) (car info) type))))
(define sql_coerce_case_args (lambda (infos type)
	(match infos
		'(last) (list (sql_coerce_info last type))
		(cons condition (cons value rest)) (cons (car condition) (cons (sql_coerce_info value type) (sql_coerce_case_args rest type)))
		_ '())))

(define sql_union_coerce_fields (lambda (fields own target)
	(match fields
		(cons title (cons expr rest)) (begin
			(define info (cadr own))
			(define result (cadr target))
			(define converted (sql_coerce_info (sql_info expr (cadr info) (sql_info_collation info)) (cadr result)))
			(cons title (cons
				(if (and (equal? converted expr) (equal? (sql_info_collation info) (sql_info_collation result))) expr
					(list (quote sql_typed_value) converted (cadr result)
						(if (nil? (sql_info_collation result)) nil (sql_collation_name result))))
				(sql_union_coerce_fields rest (cdr (cdr own)) (cdr (cdr target))))))
		_ '())))
(define sql_union_coerce_branch (lambda (branch target)
	(if (query_block? branch)
		(make_query_block (qb_schema branch) (qb_sources branch)
			(sql_union_coerce_fields (qb_fields branch) (sql_query_result_infos branch) target)
			(qb_where branch) (qb_group branch) (qb_having branch) (qb_order branch)
			(qb_limit branch) (qb_offset branch) (qb_hidden branch) (qb_stages branch) (qb_facts branch))
		branch)))

/* Bind-variable values are request-local. Specialize only their SQL type and
record that type as a cache guard; the generated formula still reads the session.
No row sampling or captured request value enters the result contract. */
(define sql_runtime_value_type (lambda (value)
	(if (nil? value) "NULL" (if (int? value) "BIGINT" (if (number? value) "DOUBLE"
		(if (string? value) "VARCHAR" (if (or (equal? value true) (equal? value false)) "BOOLEAN" "VARCHAR")))))))
(define sql_bind_expression_types (lambda (expr planning_session)
	(if (nil? planning_session) expr
		(match expr
			((symbol quote) _value) expr
			((symbol session) key)
			(if (and (string? key) (not (strlike key "__memcp%")))
				(begin
					(define type (sql_runtime_value_type (planning_session key)))
					(planner_record_guard_condition
						(list (quote equal?) (list (quote sql_runtime_value_type) expr) type) planning_session)
					(list (quote sql_parameter_value) expr type
						(if (sql_text_type? type) "utf8mb4_unicode_520_ci" nil))) expr)
			(cons head tail) (cons (sql_bind_expression_types head planning_session)
				(map tail (lambda (item) (sql_bind_expression_types item planning_session))))
			_ expr))))

(define sql_resultfields_expr (lambda (infos)
	(list (quote resultfields) (list (quote quote) (extract_assoc infos (lambda (title info)
		(list title (sql_info_type info) (sql_collation_name info))))))))
