/* Copyright (C) 2026 Carl-Philip Hänsch
SPDX-License-Identifier: GPL-3.0-or-later */

/* Metadata procedures consume bound values and immutable schema descriptions.
No SQL is synthesized, executed, or inferred from existing row contents. */
(define tsql_odbc_fields (lambda (specs) (map specs (lambda (spec)
	(list "name" (car spec) "sql_type" (nth spec 1) "size" (nth spec 2) "precision" nil "scale" nil "nullable" (nth spec 3) "source" nil)))))
(define tsql_odbc_argument (lambda (params names name fallback) (begin
	(define ordinal (find (produceN (count names)) (lambda (i) (equal? (nth names i) name)) nil))
	(define positional (concat ordinal))
	(if (and (has_assoc? params name) (has_assoc? params positional)) (error (concat "duplicate metadata argument " name)) true)
	(if (has_assoc? params name) (get_assoc params name)
		(if (has_assoc? params positional) (get_assoc params positional) fallback)))))
(define tsql_odbc_validate_arguments (lambda (params names) (extract_assoc params (lambda (key value)
	(if (or (has? names key) (has? (map (produceN (count names)) (lambda (i) (concat i))) key)) true
		(error (concat "unknown metadata argument " key)))))))
(define tsql_odbc_pattern_regex (lambda (pattern) (begin
	(define compile (lambda (position inside)
		(if (>= position (strlen pattern)) (if inside (error "unterminated metadata pattern bracket") "")
			(begin (define character (substr pattern position 1))
				(concat (if inside
					(if (equal? character "]") "]" (if (equal? character "\\") "\\\\" character))
					(match character "%" ".*" "_" "." "[" "["
						_ (if (has? '("\\" "." "^" "$" "*" "+" "?" "(" ")" "{" "}" "|" "]") character) (concat "\\" character) character)))
					(compile (+ position 1) (if inside (not (equal? character "]")) (equal? character "["))))))))
	(concat "(?is)^" (compile 0 false) "$"))))
(define tsql_odbc_matches (lambda (value pattern use_pattern)
	(if (nil? pattern) true (if use_pattern (regexp_test value (tsql_odbc_pattern_regex pattern)) (equal?? value pattern)))))
(define tsql_odbc_database (lambda (schema qualifier)
	(if (or (nil? qualifier) (equal?? qualifier schema)) true (error "metadata qualifier must be the current database"))))
(define tsql_odbc_view_names (lambda (schema)
	(scan nil (table "system" "views")
		(list 369436175368192 (scan_boundary "equal" "database" 0 0 true true "" false)) (list schema)
		'() (lambda () true) '("name") (lambda (acc name) (cons name acc)) '() (lambda (a b) (merge a b)))))
(define tsql_odbc_tables (lambda (schema params) (begin
	(define names '("table_name" "table_owner" "table_qualifier" "table_type" "fusepattern"))
	(tsql_odbc_validate_arguments params names)
	(define table_name (tsql_odbc_argument params names "table_name" nil))
	(define owner (tsql_odbc_argument params names "table_owner" nil))
	(tsql_odbc_database schema (tsql_odbc_argument params names "table_qualifier" nil))
	(define table_type (tsql_odbc_argument params names "table_type" nil))
	(define patterns (tsql_odbc_argument params names "fusepattern" 1))
	(if (has? '(0 1 false true) patterns) true (error "invalid metadata pattern flag"))
	(define types (if (nil? table_type) '("TABLE" "VIEW" "SYSTEM TABLE")
		(map (split table_type ",") (lambda (kind) (toUpper (replace (strtrim kind) "'" ""))))))
	(if (reduce types (lambda (valid kind) (and valid (has? '("TABLE" "VIEW" "SYSTEM TABLE") kind))) true) true (error "invalid metadata table type"))
	(define tables (map (show schema) (lambda (name) (list name "TABLE"))))
	(define views (map (tsql_odbc_view_names schema) (lambda (name) (list name "VIEW"))))
	(list "fields" (tsql_odbc_fields '('("TABLE_QUALIFIER" "NVARCHAR" 128 true) '("TABLE_OWNER" "NVARCHAR" 128 false)
		'("TABLE_NAME" "NVARCHAR" 128 false) '("TABLE_TYPE" "VARCHAR" 32 false) '("REMARKS" "VARCHAR" 254 true)))
		"rows" (map (filter (sort (merge tables views) (lambda (a b) (if (equal? (cadr a) (cadr b)) (< (car a) (car b)) (< (cadr a) (cadr b)))))
			(lambda (item) (and (has? types (cadr item)) (tsql_odbc_matches "dbo" owner (not (equal? patterns 0)))
				(tsql_odbc_matches (car item) table_name (not (equal? patterns 0))))))
			(lambda (item) (list "TABLE_QUALIFIER" schema "TABLE_OWNER" "dbo" "TABLE_NAME" (car item) "TABLE_TYPE" (cadr item) "REMARKS" nil)))))))
(define tsql_odbc_type (lambda (type dimensions version) (begin
	(define type (toUpper type))
	(define temporal (get_assoc '("DATE" 1 "TIME" 2 "DATETIME" 3 "DATETIME2" 3 "SMALLDATETIME" 3) type))
	(define code (if temporal (if (equal? version 3) (+ 90 temporal) (+ 8 temporal))
		(get_assoc '("BIGINT" -5 "BINARY" -2 "VARBINARY" -3 "ROWVERSION" -2 "TIMESTAMP" -2 "BIT" -7 "BOOLEAN" -7
			"CHAR" 1 "VARCHAR" 12 "NCHAR" -8 "NVARCHAR" -9 "TEXT" -1 "NTEXT" -10 "DECIMAL" 3 "NUMERIC" 2
			"MONEY" 3 "SMALLMONEY" 3 "FLOAT" 8 "REAL" 7 "INT" 4 "INTEGER" 4 "SMALLINT" 5 "TINYINT" -6) type)))
	(if (nil? code) (error (concat "unsupported ODBC metadata type " type)) true)
	(define size (if (empty_list? dimensions) nil (car dimensions)))
	(define precision (if (has? '("TIME" "DATETIME2") type)
		(+ (if (equal? type "TIME") 8 19) (if (> (coalesceNil size 7) 0) (+ 1 (coalesceNil size 7)) 0))
		(if (has? '("NCHAR" "NVARCHAR" "CHAR" "VARCHAR" "BINARY" "VARBINARY") type) size
			(if (has? '("DECIMAL" "NUMERIC") type) size
				(get_assoc '("BIGINT" 19 "BIT" 1 "BOOLEAN" 1 "FLOAT" 15 "REAL" 7 "INT" 10 "INTEGER" 10 "SMALLINT" 5 "TINYINT" 3
					"MONEY" 19 "SMALLMONEY" 10 "DATE" 10 "TIME" 8 "DATETIME" 23 "DATETIME2" 27 "SMALLDATETIME" 16 "ROWVERSION" 8 "TIMESTAMP" 8 "TEXT" 2147483647 "NTEXT" 1073741823) type)))))
	(define scale (if temporal (if (has? '("DATE" "SMALLDATETIME") type) 0 (if (has? '("TIME" "DATETIME2") type) (coalesceNil size 7) 3))
		(if (has? '("DECIMAL" "NUMERIC") type) (match dimensions '(_ decimals) decimals _ 0)
			(if (has? '("MONEY" "SMALLMONEY") type) 4 (if (has? '("BIGINT" "INT" "INTEGER" "SMALLINT" "TINYINT" "BIT" "BOOLEAN") type) 0 nil)))))
	(list "code" code "sql_code" (if temporal 9 code) "temporal" temporal "precision" precision "scale" scale
		"length" (tsql_col_length_value type dimensions) "radix" (if (has? '("FLOAT" "REAL") type) 2
			(if (has? '("DECIMAL" "NUMERIC" "MONEY" "SMALLMONEY" "BIGINT" "INT" "INTEGER" "SMALLINT" "TINYINT") type) 10 nil))
		"octets" (if (has? '("CHAR" "VARCHAR" "NCHAR" "NVARCHAR" "TEXT" "NTEXT" "BINARY" "VARBINARY" "ROWVERSION" "TIMESTAMP") type) (tsql_col_length_value type dimensions) nil)))))
(define tsql_odbc_columns (lambda (schema params session) (begin
	(define names '("table_name" "table_owner" "table_qualifier" "column_name" "odbcver"))
	(tsql_odbc_validate_arguments params names)
	(define table_name (tsql_odbc_argument params names "table_name" nil))
	(if (nil? table_name) (error "sp_columns requires table_name") true)
	(define owner (tsql_odbc_argument params names "table_owner" nil))
	(tsql_odbc_database schema (tsql_odbc_argument params names "table_qualifier" nil))
	(define column_name (tsql_odbc_argument params names "column_name" nil))
	(define version (tsql_odbc_argument params names "odbcver" 2))
	(if (has? '(2 3) version) true (error "ODBC metadata version must be 2 or 3"))
	(list "fields" (tsql_odbc_fields '('("TABLE_QUALIFIER" "NVARCHAR" 128 true) '("TABLE_OWNER" "NVARCHAR" 128 true)
		'("TABLE_NAME" "NVARCHAR" 128 false) '("COLUMN_NAME" "NVARCHAR" 128 false) '("DATA_TYPE" "SMALLINT" nil false)
		'("TYPE_NAME" "NVARCHAR" 128 false) '("PRECISION" "INT" nil true) '("LENGTH" "INT" nil true) '("SCALE" "SMALLINT" nil true)
		'("RADIX" "SMALLINT" nil true) '("NULLABLE" "SMALLINT" nil false) '("REMARKS" "VARCHAR" 254 true)
		'("COLUMN_DEF" "NVARCHAR" 4000 true) '("SQL_DATA_TYPE" "SMALLINT" nil false) '("SQL_DATETIME_SUB" "SMALLINT" nil true)
		'("CHAR_OCTET_LENGTH" "INT" nil true) '("ORDINAL_POSITION" "INT" nil false) '("IS_NULLABLE" "VARCHAR" 254 false)
		'("SS_DATA_TYPE" "TINYINT" nil true)))
		"rows" (merge (map (sort (filter (merge (show schema) (tsql_odbc_view_names schema)) (lambda (name) (and (tsql_odbc_matches "dbo" owner true) (tsql_odbc_matches name table_name true)))) <)
			(lambda (name) (filter (mapIndex (filter (tsql_odbc_object_columns schema name session) (lambda (col) (not (internal_column_name? (col "Field"))))) (lambda (ordinal col) (begin
				(define declared (coalesceNil (col "SQLDeclaredType") ""))
				(define type (toUpper (if (equal? declared "") (col "RawType") declared)))
				(define info (tsql_odbc_type type (col "Dimensions") version))
				(define alias (find (sql_type_aliases schema) (lambda (alias) (equal? (alias "ID") (col "SQLAliasID"))) nil))
				(list "TABLE_QUALIFIER" schema "TABLE_OWNER" "dbo" "TABLE_NAME" name "COLUMN_NAME" (col "Field")
					"DATA_TYPE" (info "code") "TYPE_NAME" (concat (if alias (alias "Name") (toLower type)) (if (equal? (col "Extra") "auto_increment") " identity" ""))
					"PRECISION" (info "precision") "LENGTH" (info "length") "SCALE" (info "scale") "RADIX" (info "radix")
					"NULLABLE" (if (col "Null") 1 0) "REMARKS" nil "COLUMN_DEF" nil "SQL_DATA_TYPE" (info "sql_code")
					"SQL_DATETIME_SUB" (info "temporal") "CHAR_OCTET_LENGTH" (info "octets") "ORDINAL_POSITION" (+ ordinal 1)
					"IS_NULLABLE" (if (col "Null") "YES" "NO") "SS_DATA_TYPE" (get_assoc tsql_native_type_ids (toLower type))))))
				(lambda (row) (tsql_odbc_matches (row "COLUMN_NAME") column_name true)))))))))
)
(define tsql_odbc_datatype_row (lambda (type dimensions version) (begin
	(define info (tsql_odbc_type type dimensions version))
	(define textual (has? '("CHAR" "VARCHAR" "NCHAR" "NVARCHAR" "TEXT" "NTEXT") type))
	(define binary (has? '("BINARY" "VARBINARY" "ROWVERSION") type))
	(define temporal (has? '("DATE" "TIME" "DATETIME" "DATETIME2" "SMALLDATETIME") type))
	(define numerical (not (or textual binary temporal)))
	(list "TYPE_NAME" (toLower type) "DATA_TYPE" (info "code") "PRECISION" (info "precision")
		"LITERAL_PREFIX" (if (or textual temporal) "'" (if binary "0x" nil)) "LITERAL_SUFFIX" (if (or textual temporal) "'" nil)
		"CREATE_PARAMS" (if (has? '("CHAR" "VARCHAR" "NCHAR" "NVARCHAR" "BINARY" "VARBINARY") type) "length"
			(if (has? '("DECIMAL" "NUMERIC") type) "precision,scale" (if (has? '("TIME" "DATETIME2") type) "scale" nil)))
		"NULLABLE" 1 "CASE_SENSITIVE" 0 "SEARCHABLE" (if (has? '("TEXT" "NTEXT") type) 1 3)
		"UNSIGNED_ATTRIBUTE" (if numerical (if (has? '("TINYINT" "BIT") type) 1 0) nil)
		"MONEY" (if (has? '("MONEY" "SMALLMONEY") type) 1 0) "AUTO_INCREMENT" (if (has? '("INT" "BIGINT" "SMALLINT" "TINYINT") type) 1 0)
		"LOCAL_TYPE_NAME" (toLower type) "MINIMUM_SCALE" (if (nil? (info "scale")) nil (if (has? '("MONEY" "SMALLMONEY" "DATETIME") type) (info "scale") 0))
		"MAXIMUM_SCALE" (info "scale") "SQL_DATA_TYPE" (info "sql_code") "SQL_DATETIME_SUB" (info "temporal")
		"NUM_PREC_RADIX" (info "radix") "INTERVAL_PRECISION" nil "USERTYPE" (get_assoc tsql_native_type_ids (toLower type))))))
(define tsql_odbc_datatypes (lambda (schema params) (begin
	(define names '("data_type" "odbcver"))
	(tsql_odbc_validate_arguments params names)
	(define data_type (tsql_odbc_argument params names "data_type" 0))
	(define version (tsql_odbc_argument params names "odbcver" 2))
	(if (has? '(2 3) version) true (error "ODBC metadata version must be 2 or 3"))
	(define declarations (list (list "BIGINT" '()) (list "BINARY" '(8000)) (list "BIT" '()) (list "CHAR" '(8000))
		(list "DATE" '()) (list "DATETIME" '()) (list "DATETIME2" '(7)) (list "DECIMAL" '(38 38)) (list "FLOAT" '())
		(list "INT" '()) (list "MONEY" '()) (list "NCHAR" '(4000)) (list "NTEXT" '()) (list "NUMERIC" '(38 38))
		(list "NVARCHAR" '(4000)) (list "REAL" '()) (list "SMALLINT" '()) (list "SMALLMONEY" '())
		(list "SMALLDATETIME" '()) (list "TEXT" '()) (list "TIME" '(7)) (list "TINYINT" '())
		(list "VARBINARY" '(8000)) (list "VARCHAR" '(8000))))
	(define rows (map declarations (lambda (declaration) (tsql_odbc_datatype_row (car declaration) (cadr declaration) version))))
	(list "fields" (tsql_odbc_fields '( '("TYPE_NAME" "NVARCHAR" 128 false) '("DATA_TYPE" "SMALLINT" nil false) '("PRECISION" "INT" nil true) '("LITERAL_PREFIX" "VARCHAR" 32 true) '("LITERAL_SUFFIX" "VARCHAR" 32 true) '("CREATE_PARAMS" "VARCHAR" 32 true) '("NULLABLE" "SMALLINT" nil false) '("CASE_SENSITIVE" "SMALLINT" nil false) '("SEARCHABLE" "SMALLINT" nil false) '("UNSIGNED_ATTRIBUTE" "SMALLINT" nil true) '("MONEY" "SMALLINT" nil false) '("AUTO_INCREMENT" "SMALLINT" nil true) '("LOCAL_TYPE_NAME" "NVARCHAR" 128 true) '("MINIMUM_SCALE" "SMALLINT" nil true) '("MAXIMUM_SCALE" "SMALLINT" nil true) '("SQL_DATA_TYPE" "SMALLINT" nil false) '("SQL_DATETIME_SUB" "SMALLINT" nil true) '("NUM_PREC_RADIX" "INT" nil true) '("INTERVAL_PRECISION" "SMALLINT" nil true) '("USERTYPE" "SMALLINT" nil true)))
		"rows" (sort (filter rows (lambda (row) (or (equal? data_type 0) (equal? (row "DATA_TYPE") data_type))))
			(lambda (a b) (if (equal? (a "DATA_TYPE") (b "DATA_TYPE")) (< (a "TYPE_NAME") (b "TYPE_NAME")) (< (a "DATA_TYPE") (b "DATA_TYPE")))))))))
/* Parameter discovery examines neutral SELECT expressions. Unknown contexts
fail explicitly; the query is never evaluated or physically lowered. */
(define tsql_metadata_parameter (lambda (expression) (match expression
	((symbol if) ((symbol session) bound) ((symbol session) key) ((symbol error) message))
	(if (and (strlike key "tsql_param:%") (equal? bound (concat "tsql_bound:" (substr key 11))))
		(list (substr key 11) (substr message 25)) nil)
	_ nil)))
(define tsql_metadata_declaration (lambda (schema spec) (begin
	(define alias (sql_type_alias schema (car spec)))
	(if alias (list "type" (alias "BaseType") "dimensions" (alias "Dimensions") "alias" alias)
		(list "type" (if (equal? (car spec) "INTEGER") "INT" (car spec)) "dimensions" (cadr (tsql_native_type spec)) "alias" nil)))))
(define tsql_metadata_column (lambda (schema sources expression declarations) (match expression
	((symbol get_column) alias _ name _) (begin
		(define columns (merge (map sources (lambda (source)
			(if (and (or (nil? alias) (equal?? alias (source_alias source))) (string? (source_relation source)))
				(filter (tsql_get_schema (source_schema source) (source_relation source)) (lambda (column) (equal?? (column "Field") name))) '())))))
		(if (> (count columns) 1) (error "ambiguous parameter comparison column") true)
		(if (empty_list? columns) nil (begin
			(define column (car columns))
			(define declared (coalesceNil (column "SQLDeclaredType") ""))
			(define type (toUpper (if (equal? declared "") (column "RawType") declared)))
			(define alias_type (find (sql_type_aliases schema) (lambda (candidate) (equal? (candidate "ID") (column "SQLAliasID"))) nil))
			(list "type" (if (has? '("ROWVERSION" "TIMESTAMP") type) "BINARY" type) "dimensions" (column "Dimensions") "alias" alias_type))))
	((symbol tsql_cast_value) _ ((symbol quote) spec)) (tsql_metadata_declaration schema spec)
	((symbol tsql_cast_bound) _ _source ((symbol quote) spec)) (tsql_metadata_declaration schema spec)
	((symbol tsql_convert_bound) _ _source ((symbol quote) spec) _style) (tsql_metadata_declaration schema spec)
	_ (begin (define parameter (tsql_metadata_parameter expression))
		(if parameter (get_assoc declarations (car parameter)) nil)))))
(define tsql_odbc_object_columns (lambda (schema name session) (begin
	(define view (sql_find_view schema name))
	(if (nil? view) (tsql_get_schema schema name) (begin
		(define query (normalize_query_ast (sql_expand_views (json_decode_scmer (nth view 2)) (sql_policy (session "username")))))
		(if (query_block? query) true (error "view column metadata currently requires one query block"))
		(merge (extract_assoc (expand_query_block_fields (qb_sources query) (qb_fields query)) (lambda (name expression) (begin
			(define description (tsql_metadata_column schema (qb_sources query) expression '()))
			(if description true (error "view expression type is unknown"))
			(define alias (description "alias"))
			(list (list "Field" name "RawType" (description "type") "SQLDeclaredType" (description "type")
				"Dimensions" (description "dimensions") "Null" true "SQLAliasID" (if alias (alias "ID") 0))))))))))))
(define tsql_metadata_constraints (lambda (schema node sources expected declarations) (begin
	(define parameter (tsql_metadata_parameter node))
	(if parameter (list (list (car parameter) (cadr parameter) expected))
		(match node
			((symbol query-block) _ local_sources fields condition group having ordering limit offset _hidden _stages _facts)
			(begin
				(map local_sources (lambda (source)
					(if (and (string? (source_relation source)) (not (tsql_catalog_database (source_schema source))))
						(if (table (source_schema source) (source_relation source)) true (error "unknown table in parameter description")) true)))
				(merge (merge (map local_sources (lambda (source)
					(merge (if (string? (source_relation source)) '() (tsql_metadata_constraints schema (source_relation source) '() nil declarations))
						(tsql_metadata_constraints schema (source_join_expr source) local_sources nil declarations)))))
					(merge (map (list fields condition group having ordering limit offset) (lambda (part)
						(tsql_metadata_constraints schema part local_sources nil declarations))))))
			((symbol get_column) _alias _case _name _name_case)
			(if (tsql_metadata_column schema sources node declarations) '() (error "unsupported or unknown column in parameter description"))
			((symbol union-block) _ branches _order _limit _offset _facts)
			(merge (map branches (lambda (part) (tsql_metadata_constraints schema part sources nil declarations))))
			((symbol tsql_cast_bound) input _source ((symbol quote) spec))
			(tsql_metadata_constraints schema input sources (tsql_metadata_declaration schema spec) declarations)
			((symbol tsql_convert_bound) input _source ((symbol quote) spec) _style)
			(tsql_metadata_constraints schema input sources (tsql_metadata_declaration schema spec) declarations)
			((symbol tsql_cast_value) input ((symbol quote) spec))
			(tsql_metadata_constraints schema input sources (tsql_metadata_declaration schema spec) declarations)
			((symbol tsql_convert_value) input ((symbol quote) spec) _style _source_type)
			(tsql_metadata_constraints schema input sources (tsql_metadata_declaration schema spec) declarations)
			((symbol tsql_compare_bound) _operator left right _left_spec _right_spec)
			(merge (tsql_metadata_constraints schema left sources (tsql_metadata_column schema sources right declarations) declarations)
				(tsql_metadata_constraints schema right sources (tsql_metadata_column schema sources left declarations) declarations))
			(cons operator '(left right))
			(if (has? '(equal?? < > <= >=) operator)
				(merge (tsql_metadata_constraints schema left sources (tsql_metadata_column schema sources right declarations) declarations)
					(tsql_metadata_constraints schema right sources (tsql_metadata_column schema sources left declarations) declarations))
				(merge (map (list left right) (lambda (part) (tsql_metadata_constraints schema part sources nil declarations)))))
			((symbol quote) _value) '()
			(cons _head rest) (merge (map rest (lambda (part) (tsql_metadata_constraints schema part sources nil declarations))))
			_ '())))))
(define tsql_metadata_declared_parameters (lambda (schema text)
	(if (or (nil? text) (equal? text "")) '()
		(merge (map (tsql_parse_declarations text schema) (lambda (entry)
			(list (car entry) (tsql_metadata_declaration schema (cadr entry)))))))))
(define tsql_metadata_parameter_row (lambda (schema ordinal entry) (begin
	(define declaration (nth entry 2))
	(define type (declaration "type"))
	(define dimensions (declaration "dimensions"))
	(define alias (declaration "alias"))
	(define info (tsql_odbc_type type dimensions 3))
	(define system_name (concat (toLower type) (if (empty_list? dimensions) "" (concat "(" (if (equal? (car dimensions) -1) "max" (concat (car dimensions)))
		(match dimensions '(_ scale) (concat "," scale) _ "") ")"))))
	(define length (info "length"))
	(list "parameter_ordinal" (+ ordinal 1) "name" (concat "@" (nth entry 1)) "suggested_system_type_id" (get_assoc tsql_native_type_ids (toLower type))
		"suggested_system_type_name" system_name "suggested_max_length" length
		"suggested_precision" (if (has? '("FLOAT" "REAL") type) (if (equal? type "FLOAT") 53 24)
			(if (has? '("CHAR" "VARCHAR" "NCHAR" "NVARCHAR" "BINARY" "VARBINARY" "TEXT" "NTEXT") type) 0 (coalesceNil (info "precision") 0)))
		"suggested_scale" (coalesceNil (info "scale") 0) "suggested_user_type_id" (if alias (alias "ID") nil)
		"suggested_user_type_database" (if alias schema nil) "suggested_user_type_schema" (if alias "dbo" nil) "suggested_user_type_name" (if alias (alias "Name") nil)
		"suggested_assembly_qualified_type_name" nil "suggested_xml_collection_id" nil "suggested_xml_collection_database" nil
		"suggested_xml_collection_schema" nil "suggested_xml_collection_name" nil "suggested_is_xml_document" 0
		"suggested_is_case_sensitive" 0 "suggested_is_fixed_length_clr_type" 0 "suggested_is_input" 1 "suggested_is_output" 0 "formal_parameter_name" nil
		"suggested_tds_type_id" (get_assoc '("BIGINT" 38 "INT" 38 "INTEGER" 38 "SMALLINT" 38 "TINYINT" 38 "BIT" 104 "BOOLEAN" 104
			"CHAR" 175 "VARCHAR" 167 "NCHAR" 239 "NVARCHAR" 231 "BINARY" 173 "VARBINARY" 165 "DECIMAL" 106 "NUMERIC" 108
			"MONEY" 110 "SMALLMONEY" 110 "FLOAT" 109 "REAL" 109 "DATE" 40 "TIME" 41 "DATETIME2" 42 "DATETIME" 111 "SMALLDATETIME" 111) type)
		"suggested_tds_length" (if (equal? length -1) 65535 length)))))
(define tsql_odbc_describe_parameters (lambda (schema params session) (begin
	(define names '("tsql" "params"))
	(tsql_odbc_validate_arguments params names)
	(define text (tsql_odbc_argument params names "tsql" nil))
	(if (string? text) true (error "parameter description requires SQL text"))
	(define declarations (tsql_metadata_declared_parameters schema (tsql_odbc_argument params names "params" nil)))
	(define planning_session (newsession))
	(planning_session "tsql_describe_ast" true)
	(define query (parse_tsql schema text (sql_policy (session "username")) planning_session nil))
	(define constraints (tsql_metadata_constraints schema query '() nil declarations))
	(define entries (reduce constraints (lambda (acc constraint) (begin
		(define name (car constraint))
		(define previous (find acc (lambda (entry) (equal? (car entry) name)) nil))
		(if previous
			(begin (define before (nth previous 2)) (define after (nth constraint 2))
				(if (and before after (not (equal? before after))) (error (concat "conflicting parameter type contexts @" name)) true)
				(if (or before (nil? after)) acc (map acc (lambda (entry) (if (equal? (car entry) name) constraint entry)))))
			(append acc constraint)))) '()))
	(define undeclared (filter entries (lambda (entry) (not (has_assoc? declarations (car entry))))))
	(map undeclared (lambda (entry) (if (nil? (nth entry 2)) (error (concat "cannot infer parameter type @" (car entry))) true)))
	(list "fields" (tsql_odbc_fields '( '("parameter_ordinal" "INT" nil false) '("name" "NVARCHAR" 128 false) '("suggested_system_type_id" "INT" nil false) '("suggested_system_type_name" "NVARCHAR" 256 true) '("suggested_max_length" "SMALLINT" nil false) '("suggested_precision" "TINYINT" nil false) '("suggested_scale" "TINYINT" nil false) '("suggested_user_type_id" "INT" nil true) '("suggested_user_type_database" "NVARCHAR" 128 true) '("suggested_user_type_schema" "NVARCHAR" 128 true) '("suggested_user_type_name" "NVARCHAR" 128 true) '("suggested_assembly_qualified_type_name" "NVARCHAR" 4000 true) '("suggested_xml_collection_id" "INT" nil true) '("suggested_xml_collection_database" "NVARCHAR" 128 true) '("suggested_xml_collection_schema" "NVARCHAR" 128 true) '("suggested_xml_collection_name" "NVARCHAR" 128 true) '("suggested_is_xml_document" "BIT" nil false) '("suggested_is_case_sensitive" "BIT" nil false) '("suggested_is_fixed_length_clr_type" "BIT" nil false) '("suggested_is_input" "BIT" nil false) '("suggested_is_output" "BIT" nil false) '("formal_parameter_name" "NVARCHAR" 128 true) '("suggested_tds_type_id" "INT" nil false) '("suggested_tds_length" "INT" nil false)))
		"rows" (mapIndex undeclared (lambda (ordinal entry) (tsql_metadata_parameter_row schema ordinal entry)))))))
/* Key discovery uses the existing table metadata view. */
(define tsql_odbc_key_table (lambda (schema name owner qualifier) (begin
	(tsql_odbc_database schema qualifier)
	(if (string? name) true (error "metadata requires a table name"))
	(define actual (sql_resolve_table_name schema name))
	(if (and actual (or (nil? owner) (equal?? owner "dbo"))) (show (table schema actual) true) nil))))
(define tsql_odbc_pkeys (lambda (schema params) (begin
	(define names '("table_name" "table_owner" "table_qualifier"))
	(tsql_odbc_validate_arguments params names)
	(define metadata (tsql_odbc_key_table schema (tsql_odbc_argument params names "table_name" nil)
		(tsql_odbc_argument params names "table_owner" nil) (tsql_odbc_argument params names "table_qualifier" nil)))
	(list "fields" (tsql_odbc_fields '( '("TABLE_QUALIFIER" "NVARCHAR" 128 true) '("TABLE_OWNER" "NVARCHAR" 128 false)
		'("TABLE_NAME" "NVARCHAR" 128 false) '("COLUMN_NAME" "NVARCHAR" 128 false) '("KEY_SEQ" "SMALLINT" nil false) '("PK_NAME" "NVARCHAR" 128 true)))
		"rows" (if (nil? metadata) '() (merge (map (filter (metadata "Unique") (lambda (key) (equal? (key "Id") "PRIMARY")))
			(lambda (key) (mapIndex (key "Cols") (lambda (ordinal column) (list "TABLE_QUALIFIER" schema "TABLE_OWNER" "dbo"
				"TABLE_NAME" (metadata "Name") "COLUMN_NAME" column "KEY_SEQ" (+ ordinal 1) "PK_NAME" (key "Id"))))))))))))
(define tsql_odbc_statistics (lambda (schema params) (begin
	(define names '("table_name" "table_owner" "table_qualifier" "index_name" "is_unique" "accuracy"))
	(tsql_odbc_validate_arguments params names)
	(define metadata (tsql_odbc_key_table schema (tsql_odbc_argument params names "table_name" nil)
		(tsql_odbc_argument params names "table_owner" nil) (tsql_odbc_argument params names "table_qualifier" nil)))
	(define unique (toUpper (tsql_odbc_argument params names "is_unique" "")))
	(if (has? '("" "Y" "N") unique) true (error "invalid metadata uniqueness flag"))
	(if (equal? (toUpper (tsql_odbc_argument params names "accuracy" "Q")) "Q") true (error "exact index statistics are unavailable"))
	(define pattern (tsql_odbc_argument params names "index_name" "%"))
	(list "fields" (tsql_odbc_fields '( '("TABLE_QUALIFIER" "NVARCHAR" 128 true) '("TABLE_OWNER" "NVARCHAR" 128 false)
		'("TABLE_NAME" "NVARCHAR" 128 false) '("NON_UNIQUE" "SMALLINT" nil false) '("INDEX_QUALIFIER" "NVARCHAR" 128 true)
		'("INDEX_NAME" "NVARCHAR" 128 false) '("TYPE" "SMALLINT" nil false) '("SEQ_IN_INDEX" "SMALLINT" nil false)
		'("COLUMN_NAME" "NVARCHAR" 128 false) '("COLLATION" "VARCHAR" 1 true) '("CARDINALITY" "INT" nil true)
		'("PAGES" "INT" nil true) '("FILTER_CONDITION" "VARCHAR" 128 true)))
		"rows" (if (nil? metadata) '() (merge (map (sort (filter (metadata "Unique") (lambda (key) (tsql_odbc_matches (key "Id") pattern true)))
			(lambda (a b) (< (a "Id") (b "Id")))) (lambda (key) (mapIndex (key "Cols") (lambda (ordinal column)
				(list "TABLE_QUALIFIER" schema "TABLE_OWNER" "dbo" "TABLE_NAME" (metadata "Name") "NON_UNIQUE" 0
					"INDEX_QUALIFIER" (metadata "Name") "INDEX_NAME" (key "Id") "TYPE" 3 "SEQ_IN_INDEX" (+ ordinal 1)
					"COLUMN_NAME" column "COLLATION" "A" "CARDINALITY" nil "PAGES" nil "FILTER_CONDITION" nil)))))))))))
(define tsql_odbc_special_columns (lambda (schema params) (begin
	(define names '("table_name" "table_owner" "table_qualifier" "col_type" "scope" "nullable" "odbcver"))
	(define params (if (has_assoc? params "qualifier")
		(if (has_assoc? params "table_qualifier") (error "duplicate metadata qualifier")
			(set_assoc (filter_assoc params (lambda (key _value) (not (equal? key "qualifier")))) "table_qualifier" (params "qualifier"))) params))
	(tsql_odbc_validate_arguments params names)
	(define metadata (tsql_odbc_key_table schema (tsql_odbc_argument params names "table_name" nil)
		(tsql_odbc_argument params names "table_owner" nil) (tsql_odbc_argument params names "table_qualifier" nil)))
	(define kind (toUpper (tsql_odbc_argument params names "col_type" "R")))
	(define scope (toUpper (tsql_odbc_argument params names "scope" "T")))
	(define nullable (toUpper (tsql_odbc_argument params names "nullable" "U")))
	(define version (tsql_odbc_argument params names "odbcver" 2))
	(if (and (has? '("R" "V") kind) (has? '("C" "T") scope) (has? '("U" "O") nullable) (has? '(2 3) version)) true (error "invalid special-column metadata options"))
	(define columns (if (nil? metadata) '() (metadata "Columns")))
	(define resolve (lambda (name) (find columns (lambda (column) (equal? (column "Field") name)) nil)))
	(define keys (if (nil? metadata) '() (filter (metadata "Unique") (lambda (key)
		(reduce (key "Cols") (lambda (valid name) (and valid (not ((resolve name) "Null")))) true)))))
	(define key (find keys (lambda (key) (equal? (key "Id") "PRIMARY"))
		(if (empty_list? keys) nil (car (sort keys (lambda (a b) (if (equal? (count (a "Cols")) (count (b "Cols"))) (< (a "Id") (b "Id")) (< (count (a "Cols")) (count (b "Cols"))))))))))
	(define selected (if (equal? kind "V") (filter columns (lambda (column) (and (column "RowVersion") (or (equal? nullable "U") (not (column "Null"))))))
		(if (nil? key) '() (map (key "Cols") resolve))))
	(list "fields" (tsql_odbc_fields '( '("SCOPE" "SMALLINT" nil true) '("COLUMN_NAME" "NVARCHAR" 128 false) '("DATA_TYPE" "SMALLINT" nil false)
		'("TYPE_NAME" "NVARCHAR" 128 false) '("PRECISION" "INT" nil true) '("LENGTH" "INT" nil true) '("SCALE" "SMALLINT" nil true) '("PSEUDO_COLUMN" "SMALLINT" nil false)))
		"rows" (map selected (lambda (column) (begin
			(define type (toUpper (if (equal? (coalesceNil (column "SQLDeclaredType") "") "") (column "RawType") (column "SQLDeclaredType"))))
			(define info (tsql_odbc_type type (column "Dimensions") version))
			(list "SCOPE" 0 "COLUMN_NAME" (column "Field") "DATA_TYPE" (info "code") "TYPE_NAME" (toLower type)
				"PRECISION" (info "precision") "LENGTH" (info "length") "SCALE" (info "scale") "PSEUDO_COLUMN" 1))))))))
(define tsql_odbc_fkeys (lambda (schema params) (begin
	(define names '("pktable_name" "pktable_owner" "pktable_qualifier" "fktable_name" "fktable_owner" "fktable_qualifier"))
	(tsql_odbc_validate_arguments params names)
	(tsql_odbc_database schema (tsql_odbc_argument params names "pktable_qualifier" nil))
	(tsql_odbc_database schema (tsql_odbc_argument params names "fktable_qualifier" nil))
	(define primary (tsql_odbc_argument params names "pktable_name" nil))
	(define foreign (tsql_odbc_argument params names "fktable_name" nil))
	(if (or (string? primary) (string? foreign)) true (error "foreign-key metadata requires a table name"))
	(define owners (and (tsql_odbc_matches "dbo" (tsql_odbc_argument params names "pktable_owner" nil) false)
		(tsql_odbc_matches "dbo" (tsql_odbc_argument params names "fktable_owner" nil) false)))
	(define catalog (map (show schema) (lambda (name) (show (table schema name) true))))
	(define selected (filter catalog (lambda (item) (and owners (tsql_odbc_matches (item "Name") foreign false)))))
	(define rule (lambda (mode) (match mode "cascade" 0 "set null" 2 _ 1)))
	(list "fields" (tsql_odbc_fields '( '("PKTABLE_QUALIFIER" "NVARCHAR" 128 true) '("PKTABLE_OWNER" "NVARCHAR" 128 false) '("PKTABLE_NAME" "NVARCHAR" 128 false) '("PKCOLUMN_NAME" "NVARCHAR" 128 false)
		'("FKTABLE_QUALIFIER" "NVARCHAR" 128 true) '("FKTABLE_OWNER" "NVARCHAR" 128 false) '("FKTABLE_NAME" "NVARCHAR" 128 false) '("FKCOLUMN_NAME" "NVARCHAR" 128 false)
		'("KEY_SEQ" "SMALLINT" nil false) '("UPDATE_RULE" "SMALLINT" nil false) '("DELETE_RULE" "SMALLINT" nil false) '("FK_NAME" "NVARCHAR" 128 true) '("PK_NAME" "NVARCHAR" 128 true)))
		"rows" (merge (map selected (lambda (item) (merge (map (sort (filter (item "ForeignKeys") (lambda (key) (and (equal? (key "Role") "referencing") (tsql_odbc_matches (key "OtherTable") primary false))))
			(lambda (a b) (< (a "Id") (b "Id")))) (lambda (key) (begin
				(define parent (find catalog (lambda (candidate) (equal? (candidate "Name") (key "OtherTable"))) nil))
				(define referenced (if (nil? parent) nil (find (parent "Unique") (lambda (candidate) (equal? (candidate "Cols") (key "OtherColumns"))) nil)))
				(mapIndex (key "LocalColumns") (lambda (ordinal column) (list
					"PKTABLE_QUALIFIER" schema "PKTABLE_OWNER" "dbo" "PKTABLE_NAME" (key "OtherTable") "PKCOLUMN_NAME" (nth (key "OtherColumns") ordinal)
					"FKTABLE_QUALIFIER" schema "FKTABLE_OWNER" "dbo" "FKTABLE_NAME" (item "Name") "FKCOLUMN_NAME" column "KEY_SEQ" (+ ordinal 1)
					"UPDATE_RULE" (rule (key "UpdateMode")) "DELETE_RULE" (rule (key "DeleteMode")) "FK_NAME" (key "Id") "PK_NAME" (if referenced (referenced "Id") nil)))))))))))))))
(define tsql_metadata_rpc (lambda (schema name params session) (begin
	(if (and session (session "username")) ((sql_policy (session "username")) schema true false) (error "metadata requires an authenticated session"))
	(match (toLower name)
		"sp_describe_undeclared_parameters" (tsql_odbc_describe_parameters schema params session)
		"sp_pkeys" (tsql_odbc_pkeys schema params)
		"sp_statistics" (tsql_odbc_statistics schema params)
		"sp_special_columns" (tsql_odbc_special_columns schema params)
		"sp_fkeys" (tsql_odbc_fkeys schema params)
		"sp_tables" (tsql_odbc_tables schema params)
		"sp_columns" (tsql_odbc_columns schema params session)
		"sp_datatype_info" (tsql_odbc_datatypes schema params)
		"sp_datatype_info_100" (tsql_odbc_datatypes schema params)
		_ (error (concat "unsupported metadata procedure " name))))))
(define tsql_metadata_emit (lambda (schema name params session resultrow resultfields) (begin
	(define metadata (tsql_metadata_rpc schema name params session))
	(resultfields (map (metadata "fields") (lambda (field) (field "name"))) (metadata "fields"))
	(map (metadata "rows") resultrow)
	nil)))
