#!/bin/sh
# Copyright (C) 2026 Carl-Philip Haensch
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

set -eu

case "${1:-}" in
	remove|deconfigure|upgrade)
		# Stop before replacing the binary so the old process can finish its
		# graceful shutdown rebuild. deb-systemd-invoke honours policy-rc.d.
		if [ -d /run/systemd/system ]; then
			deb-systemd-invoke stop memcp.service >/dev/null || true
		fi
		;;
esac

exit 0
