; Copyright (C) 2026 Carl-Philip Hänsch
; SPDX-License-Identifier: GPL-3.0-or-later
; The packaged host resolves extension_dir beside its private libphp runtime.
; Application limits and OPcache settings remain in the MemCP dashboard.
extension=imagick.so
